// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Enums/GenericClickTelemetryIds.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Enums {

  /// <summary>Holder for reflection information generated from POGOProtos/Enums/GenericClickTelemetryIds.proto</summary>
  public static partial class GenericClickTelemetryIdsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Enums/GenericClickTelemetryIds.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GenericClickTelemetryIdsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9QT0dPUHJvdG9zL0VudW1zL0dlbmVyaWNDbGlja1RlbGVtZXRyeUlkcy5w",
            "cm90bxIQUE9HT1Byb3Rvcy5FbnVtcypsChhHZW5lcmljQ2xpY2tUZWxlbWV0",
            "cnlJZHMSGwoXVU5ERUZJTkVEX0dFTkVSSUNfRVZFTlQQABIWChJTUEVFRF9X",
            "QVJOSU5HX1NIT1cQARIbChdTUEVFRF9XQVJOSU5HX1BBU1NFTkdFUhACYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::POGOProtos.Enums.GenericClickTelemetryIds), }, null));
    }
    #endregion

  }
  #region Enums
  public enum GenericClickTelemetryIds {
    [pbr::OriginalName("UNDEFINED_GENERIC_EVENT")] UndefinedGenericEvent = 0,
    [pbr::OriginalName("SPEED_WARNING_SHOW")] SpeedWarningShow = 1,
    [pbr::OriginalName("SPEED_WARNING_PASSENGER")] SpeedWarningPassenger = 2,
  }

  #endregion

}

#endregion Designer generated code
