// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Trading/ExcludedPokemon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Trading {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Trading/ExcludedPokemon.proto</summary>
  public static partial class ExcludedPokemonReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Trading/ExcludedPokemon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExcludedPokemonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1QT0dPUHJvdG9zL0RhdGEvVHJhZGluZy9FeGNsdWRlZFBva2Vtb24ucHJv",
            "dG8SF1BPR09Qcm90b3MuRGF0YS5UcmFkaW5nIrMDCg9FeGNsdWRlZFBva2Vt",
            "b24SEgoKcG9rZW1vbl9pZBgBIAEoBhJSChBleGNsdXNpb25fcmVhc29uGAIg",
            "ASgOMjguUE9HT1Byb3Rvcy5EYXRhLlRyYWRpbmcuRXhjbHVkZWRQb2tlbW9u",
            "LkV4Y2x1c2lvblJlYXNvbiK3AgoPRXhjbHVzaW9uUmVhc29uEgkKBVVOU0VU",
            "EAASFAoQTVlUSElDQUxfUE9LRU1PThABEgsKB1NMQVNIRUQQAhIQCgxHWU1f",
            "REVQTE9ZRUQQAxIJCgVCVUREWRAEEhQKEFNUQU1JTkFfTk9UX0ZVTEwQBRIT",
            "Cg9FR0dfTk9UX0hBVENIRUQQBhIYChRGUklFTkRTSElQX0xFVkVMX0xPVxAH",
            "EhgKFEZSSUVORF9DQU5OT1RfQUZGT1JEEAgSHgoaRlJJRU5EX1JFQUNIRURf",
            "REFJTFlfTElNSVQQCRISCg5BTFJFQURZX1RSQURFRBAKEhgKFFBMQVlFUl9D",
            "QU5OT1RfQUZGT1JEEAsSHgoaUExBWUVSX1JFQUNIRURfREFJTFlfTElNSVQQ",
            "DBIMCghGQVZPUklURRANYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Trading.ExcludedPokemon), global::POGOProtos.Data.Trading.ExcludedPokemon.Parser, new[]{ "PokemonId", "ExclusionReason" }, null, new[]{ typeof(global::POGOProtos.Data.Trading.ExcludedPokemon.Types.ExclusionReason) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ExcludedPokemon : pb::IMessage<ExcludedPokemon> {
    private static readonly pb::MessageParser<ExcludedPokemon> _parser = new pb::MessageParser<ExcludedPokemon>(() => new ExcludedPokemon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExcludedPokemon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Trading.ExcludedPokemonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExcludedPokemon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExcludedPokemon(ExcludedPokemon other) : this() {
      pokemonId_ = other.pokemonId_;
      exclusionReason_ = other.exclusionReason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExcludedPokemon Clone() {
      return new ExcludedPokemon(this);
    }

    /// <summary>Field number for the "pokemon_id" field.</summary>
    public const int PokemonIdFieldNumber = 1;
    private ulong pokemonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong PokemonId {
      get { return pokemonId_; }
      set {
        pokemonId_ = value;
      }
    }

    /// <summary>Field number for the "exclusion_reason" field.</summary>
    public const int ExclusionReasonFieldNumber = 2;
    private global::POGOProtos.Data.Trading.ExcludedPokemon.Types.ExclusionReason exclusionReason_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Trading.ExcludedPokemon.Types.ExclusionReason ExclusionReason {
      get { return exclusionReason_; }
      set {
        exclusionReason_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExcludedPokemon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExcludedPokemon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PokemonId != other.PokemonId) return false;
      if (ExclusionReason != other.ExclusionReason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PokemonId != 0UL) hash ^= PokemonId.GetHashCode();
      if (ExclusionReason != 0) hash ^= ExclusionReason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PokemonId != 0UL) {
        output.WriteRawTag(9);
        output.WriteFixed64(PokemonId);
      }
      if (ExclusionReason != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ExclusionReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PokemonId != 0UL) {
        size += 1 + 8;
      }
      if (ExclusionReason != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ExclusionReason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExcludedPokemon other) {
      if (other == null) {
        return;
      }
      if (other.PokemonId != 0UL) {
        PokemonId = other.PokemonId;
      }
      if (other.ExclusionReason != 0) {
        ExclusionReason = other.ExclusionReason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            PokemonId = input.ReadFixed64();
            break;
          }
          case 16: {
            exclusionReason_ = (global::POGOProtos.Data.Trading.ExcludedPokemon.Types.ExclusionReason) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ExcludedPokemon message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ExclusionReason {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("MYTHICAL_POKEMON")] MythicalPokemon = 1,
        [pbr::OriginalName("SLASHED")] Slashed = 2,
        [pbr::OriginalName("GYM_DEPLOYED")] GymDeployed = 3,
        [pbr::OriginalName("BUDDY")] Buddy = 4,
        [pbr::OriginalName("STAMINA_NOT_FULL")] StaminaNotFull = 5,
        [pbr::OriginalName("EGG_NOT_HATCHED")] EggNotHatched = 6,
        [pbr::OriginalName("FRIENDSHIP_LEVEL_LOW")] FriendshipLevelLow = 7,
        [pbr::OriginalName("FRIEND_CANNOT_AFFORD")] FriendCannotAfford = 8,
        [pbr::OriginalName("FRIEND_REACHED_DAILY_LIMIT")] FriendReachedDailyLimit = 9,
        [pbr::OriginalName("ALREADY_TRADED")] AlreadyTraded = 10,
        [pbr::OriginalName("PLAYER_CANNOT_AFFORD")] PlayerCannotAfford = 11,
        [pbr::OriginalName("PLAYER_REACHED_DAILY_LIMIT")] PlayerReachedDailyLimit = 12,
        [pbr::OriginalName("FAVORITE")] Favorite = 13,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
