// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Battle/BattleParticipant.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Battle {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Battle/BattleParticipant.proto</summary>
  public static partial class BattleParticipantReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Battle/BattleParticipant.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleParticipantReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5QT0dPUHJvdG9zL0RhdGEvQmF0dGxlL0JhdHRsZVBhcnRpY2lwYW50LnBy",
            "b3RvEhZQT0dPUHJvdG9zLkRhdGEuQmF0dGxlGi5QT0dPUHJvdG9zL0RhdGEv",
            "QmF0dGxlL0JhdHRsZVBva2Vtb25JbmZvLnByb3RvGjBQT0dPUHJvdG9zL0Rh",
            "dGEvUGxheWVyL1BsYXllclB1YmxpY1Byb2ZpbGUucHJvdG8aKVBPR09Qcm90",
            "b3MvTWFwL1Bva2Vtb24vTG9iYnlQb2tlbW9uLnByb3RvGi9QT0dPUHJvdG9z",
            "L0VudW1zL0ZyaWVuZHNoaXBMZXZlbE1pbGVzdG9uZS5wcm90byKoBAoRQmF0",
            "dGxlUGFydGljaXBhbnQSQQoOYWN0aXZlX3Bva2Vtb24YASABKAsyKS5QT0dP",
            "UHJvdG9zLkRhdGEuQmF0dGxlLkJhdHRsZVBva2Vtb25JbmZvEksKFnRyYWlu",
            "ZXJfcHVibGljX3Byb2ZpbGUYAiABKAsyKy5QT0dPUHJvdG9zLkRhdGEuUGxh",
            "eWVyLlBsYXllclB1YmxpY1Byb2ZpbGUSQgoPcmV2ZXJzZV9wb2tlbW9uGAMg",
            "AygLMikuUE9HT1Byb3Rvcy5EYXRhLkJhdHRsZS5CYXR0bGVQb2tlbW9uSW5m",
            "bxJDChBkZWZlYXRlZF9wb2tlbW9uGAQgAygLMikuUE9HT1Byb3Rvcy5EYXRh",
            "LkJhdHRsZS5CYXR0bGVQb2tlbW9uSW5mbxI7Cg1sb2JieV9wb2tlbW9uGAUg",
            "AygLMiQuUE9HT1Byb3Rvcy5NYXAuUG9rZW1vbi5Mb2JieVBva2Vtb24SFAoM",
            "ZGFtYWdlX2RlYWx0GAYgASgFEiMKG3N1cGVyX2VmZmVjdGl2ZV9jaGFyZ2Vf",
            "bW92ZRgHIAEoCBIXCg93ZWF0aGVyX2Jvb3N0ZWQYCCABKAgSUAocaGlnaGVz",
            "dF9mcmllbmRzaGlwX21pbGVzdG9uZRgJIAEoDjIqLlBPR09Qcm90b3MuRW51",
            "bXMuRnJpZW5kc2hpcExldmVsTWlsZXN0b25lEhcKD2ZyaWVuZF9jb2RlbmFt",
            "ZRgKIAMoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Battle.BattlePokemonInfoReflection.Descriptor, global::POGOProtos.Data.Player.PlayerPublicProfileReflection.Descriptor, global::POGOProtos.Map.Pokemon.LobbyPokemonReflection.Descriptor, global::POGOProtos.Enums.FriendshipLevelMilestoneReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Battle.BattleParticipant), global::POGOProtos.Data.Battle.BattleParticipant.Parser, new[]{ "ActivePokemon", "TrainerPublicProfile", "ReversePokemon", "DefeatedPokemon", "LobbyPokemon", "DamageDealt", "SuperEffectiveChargeMove", "WeatherBoosted", "HighestFriendshipMilestone", "FriendCodename" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BattleParticipant : pb::IMessage<BattleParticipant> {
    private static readonly pb::MessageParser<BattleParticipant> _parser = new pb::MessageParser<BattleParticipant>(() => new BattleParticipant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattleParticipant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Battle.BattleParticipantReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleParticipant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleParticipant(BattleParticipant other) : this() {
      activePokemon_ = other.activePokemon_ != null ? other.activePokemon_.Clone() : null;
      trainerPublicProfile_ = other.trainerPublicProfile_ != null ? other.trainerPublicProfile_.Clone() : null;
      reversePokemon_ = other.reversePokemon_.Clone();
      defeatedPokemon_ = other.defeatedPokemon_.Clone();
      lobbyPokemon_ = other.lobbyPokemon_.Clone();
      damageDealt_ = other.damageDealt_;
      superEffectiveChargeMove_ = other.superEffectiveChargeMove_;
      weatherBoosted_ = other.weatherBoosted_;
      highestFriendshipMilestone_ = other.highestFriendshipMilestone_;
      friendCodename_ = other.friendCodename_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleParticipant Clone() {
      return new BattleParticipant(this);
    }

    /// <summary>Field number for the "active_pokemon" field.</summary>
    public const int ActivePokemonFieldNumber = 1;
    private global::POGOProtos.Data.Battle.BattlePokemonInfo activePokemon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Battle.BattlePokemonInfo ActivePokemon {
      get { return activePokemon_; }
      set {
        activePokemon_ = value;
      }
    }

    /// <summary>Field number for the "trainer_public_profile" field.</summary>
    public const int TrainerPublicProfileFieldNumber = 2;
    private global::POGOProtos.Data.Player.PlayerPublicProfile trainerPublicProfile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Player.PlayerPublicProfile TrainerPublicProfile {
      get { return trainerPublicProfile_; }
      set {
        trainerPublicProfile_ = value;
      }
    }

    /// <summary>Field number for the "reverse_pokemon" field.</summary>
    public const int ReversePokemonFieldNumber = 3;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Battle.BattlePokemonInfo> _repeated_reversePokemon_codec
        = pb::FieldCodec.ForMessage(26, global::POGOProtos.Data.Battle.BattlePokemonInfo.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> reversePokemon_ = new pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> ReversePokemon {
      get { return reversePokemon_; }
    }

    /// <summary>Field number for the "defeated_pokemon" field.</summary>
    public const int DefeatedPokemonFieldNumber = 4;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Battle.BattlePokemonInfo> _repeated_defeatedPokemon_codec
        = pb::FieldCodec.ForMessage(34, global::POGOProtos.Data.Battle.BattlePokemonInfo.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> defeatedPokemon_ = new pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> DefeatedPokemon {
      get { return defeatedPokemon_; }
    }

    /// <summary>Field number for the "lobby_pokemon" field.</summary>
    public const int LobbyPokemonFieldNumber = 5;
    private static readonly pb::FieldCodec<global::POGOProtos.Map.Pokemon.LobbyPokemon> _repeated_lobbyPokemon_codec
        = pb::FieldCodec.ForMessage(42, global::POGOProtos.Map.Pokemon.LobbyPokemon.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Map.Pokemon.LobbyPokemon> lobbyPokemon_ = new pbc::RepeatedField<global::POGOProtos.Map.Pokemon.LobbyPokemon>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Map.Pokemon.LobbyPokemon> LobbyPokemon {
      get { return lobbyPokemon_; }
    }

    /// <summary>Field number for the "damage_dealt" field.</summary>
    public const int DamageDealtFieldNumber = 6;
    private int damageDealt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DamageDealt {
      get { return damageDealt_; }
      set {
        damageDealt_ = value;
      }
    }

    /// <summary>Field number for the "super_effective_charge_move" field.</summary>
    public const int SuperEffectiveChargeMoveFieldNumber = 7;
    private bool superEffectiveChargeMove_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool SuperEffectiveChargeMove {
      get { return superEffectiveChargeMove_; }
      set {
        superEffectiveChargeMove_ = value;
      }
    }

    /// <summary>Field number for the "weather_boosted" field.</summary>
    public const int WeatherBoostedFieldNumber = 8;
    private bool weatherBoosted_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool WeatherBoosted {
      get { return weatherBoosted_; }
      set {
        weatherBoosted_ = value;
      }
    }

    /// <summary>Field number for the "highest_friendship_milestone" field.</summary>
    public const int HighestFriendshipMilestoneFieldNumber = 9;
    private global::POGOProtos.Enums.FriendshipLevelMilestone highestFriendshipMilestone_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Enums.FriendshipLevelMilestone HighestFriendshipMilestone {
      get { return highestFriendshipMilestone_; }
      set {
        highestFriendshipMilestone_ = value;
      }
    }

    /// <summary>Field number for the "friend_codename" field.</summary>
    public const int FriendCodenameFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _repeated_friendCodename_codec
        = pb::FieldCodec.ForString(82);
    private readonly pbc::RepeatedField<string> friendCodename_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> FriendCodename {
      get { return friendCodename_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattleParticipant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattleParticipant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ActivePokemon, other.ActivePokemon)) return false;
      if (!object.Equals(TrainerPublicProfile, other.TrainerPublicProfile)) return false;
      if(!reversePokemon_.Equals(other.reversePokemon_)) return false;
      if(!defeatedPokemon_.Equals(other.defeatedPokemon_)) return false;
      if(!lobbyPokemon_.Equals(other.lobbyPokemon_)) return false;
      if (DamageDealt != other.DamageDealt) return false;
      if (SuperEffectiveChargeMove != other.SuperEffectiveChargeMove) return false;
      if (WeatherBoosted != other.WeatherBoosted) return false;
      if (HighestFriendshipMilestone != other.HighestFriendshipMilestone) return false;
      if(!friendCodename_.Equals(other.friendCodename_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (activePokemon_ != null) hash ^= ActivePokemon.GetHashCode();
      if (trainerPublicProfile_ != null) hash ^= TrainerPublicProfile.GetHashCode();
      hash ^= reversePokemon_.GetHashCode();
      hash ^= defeatedPokemon_.GetHashCode();
      hash ^= lobbyPokemon_.GetHashCode();
      if (DamageDealt != 0) hash ^= DamageDealt.GetHashCode();
      if (SuperEffectiveChargeMove != false) hash ^= SuperEffectiveChargeMove.GetHashCode();
      if (WeatherBoosted != false) hash ^= WeatherBoosted.GetHashCode();
      if (HighestFriendshipMilestone != 0) hash ^= HighestFriendshipMilestone.GetHashCode();
      hash ^= friendCodename_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (activePokemon_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ActivePokemon);
      }
      if (trainerPublicProfile_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrainerPublicProfile);
      }
      reversePokemon_.WriteTo(output, _repeated_reversePokemon_codec);
      defeatedPokemon_.WriteTo(output, _repeated_defeatedPokemon_codec);
      lobbyPokemon_.WriteTo(output, _repeated_lobbyPokemon_codec);
      if (DamageDealt != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(DamageDealt);
      }
      if (SuperEffectiveChargeMove != false) {
        output.WriteRawTag(56);
        output.WriteBool(SuperEffectiveChargeMove);
      }
      if (WeatherBoosted != false) {
        output.WriteRawTag(64);
        output.WriteBool(WeatherBoosted);
      }
      if (HighestFriendshipMilestone != 0) {
        output.WriteRawTag(72);
        output.WriteEnum((int) HighestFriendshipMilestone);
      }
      friendCodename_.WriteTo(output, _repeated_friendCodename_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (activePokemon_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActivePokemon);
      }
      if (trainerPublicProfile_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrainerPublicProfile);
      }
      size += reversePokemon_.CalculateSize(_repeated_reversePokemon_codec);
      size += defeatedPokemon_.CalculateSize(_repeated_defeatedPokemon_codec);
      size += lobbyPokemon_.CalculateSize(_repeated_lobbyPokemon_codec);
      if (DamageDealt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DamageDealt);
      }
      if (SuperEffectiveChargeMove != false) {
        size += 1 + 1;
      }
      if (WeatherBoosted != false) {
        size += 1 + 1;
      }
      if (HighestFriendshipMilestone != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) HighestFriendshipMilestone);
      }
      size += friendCodename_.CalculateSize(_repeated_friendCodename_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattleParticipant other) {
      if (other == null) {
        return;
      }
      if (other.activePokemon_ != null) {
        if (activePokemon_ == null) {
          activePokemon_ = new global::POGOProtos.Data.Battle.BattlePokemonInfo();
        }
        ActivePokemon.MergeFrom(other.ActivePokemon);
      }
      if (other.trainerPublicProfile_ != null) {
        if (trainerPublicProfile_ == null) {
          trainerPublicProfile_ = new global::POGOProtos.Data.Player.PlayerPublicProfile();
        }
        TrainerPublicProfile.MergeFrom(other.TrainerPublicProfile);
      }
      reversePokemon_.Add(other.reversePokemon_);
      defeatedPokemon_.Add(other.defeatedPokemon_);
      lobbyPokemon_.Add(other.lobbyPokemon_);
      if (other.DamageDealt != 0) {
        DamageDealt = other.DamageDealt;
      }
      if (other.SuperEffectiveChargeMove != false) {
        SuperEffectiveChargeMove = other.SuperEffectiveChargeMove;
      }
      if (other.WeatherBoosted != false) {
        WeatherBoosted = other.WeatherBoosted;
      }
      if (other.HighestFriendshipMilestone != 0) {
        HighestFriendshipMilestone = other.HighestFriendshipMilestone;
      }
      friendCodename_.Add(other.friendCodename_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (activePokemon_ == null) {
              activePokemon_ = new global::POGOProtos.Data.Battle.BattlePokemonInfo();
            }
            input.ReadMessage(activePokemon_);
            break;
          }
          case 18: {
            if (trainerPublicProfile_ == null) {
              trainerPublicProfile_ = new global::POGOProtos.Data.Player.PlayerPublicProfile();
            }
            input.ReadMessage(trainerPublicProfile_);
            break;
          }
          case 26: {
            reversePokemon_.AddEntriesFrom(input, _repeated_reversePokemon_codec);
            break;
          }
          case 34: {
            defeatedPokemon_.AddEntriesFrom(input, _repeated_defeatedPokemon_codec);
            break;
          }
          case 42: {
            lobbyPokemon_.AddEntriesFrom(input, _repeated_lobbyPokemon_codec);
            break;
          }
          case 48: {
            DamageDealt = input.ReadInt32();
            break;
          }
          case 56: {
            SuperEffectiveChargeMove = input.ReadBool();
            break;
          }
          case 64: {
            WeatherBoosted = input.ReadBool();
            break;
          }
          case 72: {
            highestFriendshipMilestone_ = (global::POGOProtos.Enums.FriendshipLevelMilestone) input.ReadEnum();
            break;
          }
          case 82: {
            friendCodename_.AddEntriesFrom(input, _repeated_friendCodename_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
