// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Settings/GlobalSettings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/GlobalSettings.proto</summary>
  public static partial class GlobalSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/GlobalSettings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GlobalSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihQT0dPUHJvdG9zL1NldHRpbmdzL0dsb2JhbFNldHRpbmdzLnByb3RvEhNQ",
            "T0dPUHJvdG9zLlNldHRpbmdzGidQT0dPUHJvdG9zL1NldHRpbmdzL0V2ZW50",
            "U2V0dGluZ3MucHJvdG8aKlBPR09Qcm90b3MvU2V0dGluZ3MvRmVzdGl2YWxT",
            "ZXR0aW5ncy5wcm90bxomUE9HT1Byb3Rvcy9TZXR0aW5ncy9Gb3J0U2V0dGlu",
            "Z3MucHJvdG8aJVBPR09Qcm90b3MvU2V0dGluZ3MvR3BzU2V0dGluZ3MucHJv",
            "dG8aK1BPR09Qcm90b3MvU2V0dGluZ3MvSW52ZW50b3J5U2V0dGluZ3MucHJv",
            "dG8aJ1BPR09Qcm90b3MvU2V0dGluZ3MvTGV2ZWxTZXR0aW5ncy5wcm90bxol",
            "UE9HT1Byb3Rvcy9TZXR0aW5ncy9NYXBTZXR0aW5ncy5wcm90bxomUE9HT1By",
            "b3Rvcy9TZXR0aW5ncy9OZXdzU2V0dGluZ3MucHJvdG8aLlBPR09Qcm90b3Mv",
            "U2V0dGluZ3MvTm90aWZpY2F0aW9uU2V0dGluZ3MucHJvdG8aKlBPR09Qcm90",
            "b3MvU2V0dGluZ3MvUGFzc2NvZGVTZXR0aW5ncy5wcm90bxonUE9HT1Byb3Rv",
            "cy9TZXR0aW5ncy9TZmlkYVNldHRpbmdzLnByb3RvGi1QT0dPUHJvdG9zL1Nl",
            "dHRpbmdzL1RyYW5zbGF0aW9uU2V0dGluZ3MucHJvdG8aM1BPR09Qcm90b3Mv",
            "U2V0dGluZ3MvQ2xpZW50UGVyZm9ybWFuY2VTZXR0aW5ncy5wcm90bxosUE9H",
            "T1Byb3Rvcy9TZXR0aW5ncy9OZXdzR2xvYmFsU2V0dGluZ3MucHJvdG8aMVBP",
            "R09Qcm90b3MvU2V0dGluZ3MvVGVsZW1ldHJ5R2xvYmFsU2V0dGluZ3MucHJv",
            "dG8aJ1BPR09Qcm90b3MvU2V0dGluZ3MvTG9naW5TZXR0aW5ncy5wcm90bxot",
            "UE9HT1Byb3Rvcy9TZXR0aW5ncy9RdWVzdEdsb2JhbFNldHRpbmdzLnByb3Rv",
            "IsYJCg5HbG9iYWxTZXR0aW5ncxI4Cg1mb3J0X3NldHRpbmdzGAIgASgLMiEu",
            "UE9HT1Byb3Rvcy5TZXR0aW5ncy5Gb3J0U2V0dGluZ3MSNgoMbWFwX3NldHRp",
            "bmdzGAMgASgLMiAuUE9HT1Byb3Rvcy5TZXR0aW5ncy5NYXBTZXR0aW5ncxI6",
            "Cg5sZXZlbF9zZXR0aW5ncxgEIAEoCzIiLlBPR09Qcm90b3MuU2V0dGluZ3Mu",
            "TGV2ZWxTZXR0aW5ncxJCChJpbnZlbnRvcnlfc2V0dGluZ3MYBSABKAsyJi5Q",
            "T0dPUHJvdG9zLlNldHRpbmdzLkludmVudG9yeVNldHRpbmdzEh4KFm1pbmlt",
            "dW1fY2xpZW50X3ZlcnNpb24YBiABKAkSNgoMZ3BzX3NldHRpbmdzGAcgASgL",
            "MiAuUE9HT1Byb3Rvcy5TZXR0aW5ncy5HcHNTZXR0aW5ncxJAChFmZXN0aXZh",
            "bF9zZXR0aW5ncxgIIAEoCzIlLlBPR09Qcm90b3MuU2V0dGluZ3MuRmVzdGl2",
            "YWxTZXR0aW5ncxI6Cg5ldmVudF9zZXR0aW5ncxgJIAEoCzIiLlBPR09Qcm90",
            "b3MuU2V0dGluZ3MuRXZlbnRTZXR0aW5ncxIZChFtYXhfcG9rZW1vbl90eXBl",
            "cxgKIAEoBRI6Cg5zZmlkYV9zZXR0aW5ncxgLIAEoCzIiLlBPR09Qcm90b3Mu",
            "U2V0dGluZ3MuU2ZpZGFTZXR0aW5ncxI4Cg1uZXdzX3NldHRpbmdzGAwgASgL",
            "MiEuUE9HT1Byb3Rvcy5TZXR0aW5ncy5OZXdzU2V0dGluZ3MSRgoUdHJhbnNs",
            "YXRpb25fc2V0dGluZ3MYDSABKAsyKC5QT0dPUHJvdG9zLlNldHRpbmdzLlRy",
            "YW5zbGF0aW9uU2V0dGluZ3MSQAoRcGFzc2NvZGVfc2V0dGluZ3MYDiABKAsy",
            "JS5QT0dPUHJvdG9zLlNldHRpbmdzLlBhc3Njb2RlU2V0dGluZ3MSSAoVbm90",
            "aWZpY2F0aW9uX3NldHRpbmdzGA8gASgLMikuUE9HT1Byb3Rvcy5TZXR0aW5n",
            "cy5Ob3RpZmljYXRpb25TZXR0aW5ncxIcChRjbGllbnRfYXBwX2JsYWNrbGlz",
            "dBgQIAMoCRJMChRjbGllbnRfcGVyZl9zZXR0aW5ncxgRIAEoCzIuLlBPR09Q",
            "cm90b3MuU2V0dGluZ3MuQ2xpZW50UGVyZm9ybWFuY2VTZXR0aW5ncxJFChRu",
            "ZXdzX2dsb2JhbF9zZXR0aW5ncxgSIAEoCzInLlBPR09Qcm90b3MuU2V0dGlu",
            "Z3MuTmV3c0dsb2JhbFNldHRpbmdzEk8KGXRlbGVtZXRyeV9nbG9iYWxfc2V0",
            "dGluZ3MYFSABKAsyLC5QT0dPUHJvdG9zLlNldHRpbmdzLlRlbGVtZXRyeUds",
            "b2JhbFNldHRpbmdzEjoKDmxvZ2luX3NldHRpbmdzGBYgASgLMiIuUE9HT1By",
            "b3Rvcy5TZXR0aW5ncy5Mb2dpblNldHRpbmdzEkcKFXF1ZXN0X2dsb2JhbF9z",
            "ZXR0aW5ncxgTIAEoCzIoLlBPR09Qcm90b3MuU2V0dGluZ3MuUXVlc3RHbG9i",
            "YWxTZXR0aW5nc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Settings.EventSettingsReflection.Descriptor, global::POGOProtos.Settings.FestivalSettingsReflection.Descriptor, global::POGOProtos.Settings.FortSettingsReflection.Descriptor, global::POGOProtos.Settings.GpsSettingsReflection.Descriptor, global::POGOProtos.Settings.InventorySettingsReflection.Descriptor, global::POGOProtos.Settings.LevelSettingsReflection.Descriptor, global::POGOProtos.Settings.MapSettingsReflection.Descriptor, global::POGOProtos.Settings.NewsSettingsReflection.Descriptor, global::POGOProtos.Settings.NotificationSettingsReflection.Descriptor, global::POGOProtos.Settings.PasscodeSettingsReflection.Descriptor, global::POGOProtos.Settings.SfidaSettingsReflection.Descriptor, global::POGOProtos.Settings.TranslationSettingsReflection.Descriptor, global::POGOProtos.Settings.ClientPerformanceSettingsReflection.Descriptor, global::POGOProtos.Settings.NewsGlobalSettingsReflection.Descriptor, global::POGOProtos.Settings.TelemetryGlobalSettingsReflection.Descriptor, global::POGOProtos.Settings.LoginSettingsReflection.Descriptor, global::POGOProtos.Settings.QuestGlobalSettingsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.GlobalSettings), global::POGOProtos.Settings.GlobalSettings.Parser, new[]{ "FortSettings", "MapSettings", "LevelSettings", "InventorySettings", "MinimumClientVersion", "GpsSettings", "FestivalSettings", "EventSettings", "MaxPokemonTypes", "SfidaSettings", "NewsSettings", "TranslationSettings", "PasscodeSettings", "NotificationSettings", "ClientAppBlacklist", "ClientPerfSettings", "NewsGlobalSettings", "TelemetryGlobalSettings", "LoginSettings", "QuestGlobalSettings" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GlobalSettings : pb::IMessage<GlobalSettings> {
    private static readonly pb::MessageParser<GlobalSettings> _parser = new pb::MessageParser<GlobalSettings>(() => new GlobalSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GlobalSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.GlobalSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalSettings(GlobalSettings other) : this() {
      FortSettings = other.fortSettings_ != null ? other.FortSettings.Clone() : null;
      MapSettings = other.mapSettings_ != null ? other.MapSettings.Clone() : null;
      LevelSettings = other.levelSettings_ != null ? other.LevelSettings.Clone() : null;
      InventorySettings = other.inventorySettings_ != null ? other.InventorySettings.Clone() : null;
      minimumClientVersion_ = other.minimumClientVersion_;
      GpsSettings = other.gpsSettings_ != null ? other.GpsSettings.Clone() : null;
      FestivalSettings = other.festivalSettings_ != null ? other.FestivalSettings.Clone() : null;
      EventSettings = other.eventSettings_ != null ? other.EventSettings.Clone() : null;
      maxPokemonTypes_ = other.maxPokemonTypes_;
      SfidaSettings = other.sfidaSettings_ != null ? other.SfidaSettings.Clone() : null;
      NewsSettings = other.newsSettings_ != null ? other.NewsSettings.Clone() : null;
      TranslationSettings = other.translationSettings_ != null ? other.TranslationSettings.Clone() : null;
      PasscodeSettings = other.passcodeSettings_ != null ? other.PasscodeSettings.Clone() : null;
      NotificationSettings = other.notificationSettings_ != null ? other.NotificationSettings.Clone() : null;
      clientAppBlacklist_ = other.clientAppBlacklist_.Clone();
      ClientPerfSettings = other.clientPerfSettings_ != null ? other.ClientPerfSettings.Clone() : null;
      NewsGlobalSettings = other.newsGlobalSettings_ != null ? other.NewsGlobalSettings.Clone() : null;
      TelemetryGlobalSettings = other.telemetryGlobalSettings_ != null ? other.TelemetryGlobalSettings.Clone() : null;
      LoginSettings = other.loginSettings_ != null ? other.LoginSettings.Clone() : null;
      QuestGlobalSettings = other.questGlobalSettings_ != null ? other.QuestGlobalSettings.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GlobalSettings Clone() {
      return new GlobalSettings(this);
    }

    /// <summary>Field number for the "fort_settings" field.</summary>
    public const int FortSettingsFieldNumber = 2;
    private global::POGOProtos.Settings.FortSettings fortSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.FortSettings FortSettings {
      get { return fortSettings_; }
      set {
        fortSettings_ = value;
      }
    }

    /// <summary>Field number for the "map_settings" field.</summary>
    public const int MapSettingsFieldNumber = 3;
    private global::POGOProtos.Settings.MapSettings mapSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.MapSettings MapSettings {
      get { return mapSettings_; }
      set {
        mapSettings_ = value;
      }
    }

    /// <summary>Field number for the "level_settings" field.</summary>
    public const int LevelSettingsFieldNumber = 4;
    private global::POGOProtos.Settings.LevelSettings levelSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.LevelSettings LevelSettings {
      get { return levelSettings_; }
      set {
        levelSettings_ = value;
      }
    }

    /// <summary>Field number for the "inventory_settings" field.</summary>
    public const int InventorySettingsFieldNumber = 5;
    private global::POGOProtos.Settings.InventorySettings inventorySettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.InventorySettings InventorySettings {
      get { return inventorySettings_; }
      set {
        inventorySettings_ = value;
      }
    }

    /// <summary>Field number for the "minimum_client_version" field.</summary>
    public const int MinimumClientVersionFieldNumber = 6;
    private string minimumClientVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MinimumClientVersion {
      get { return minimumClientVersion_; }
      set {
        minimumClientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gps_settings" field.</summary>
    public const int GpsSettingsFieldNumber = 7;
    private global::POGOProtos.Settings.GpsSettings gpsSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.GpsSettings GpsSettings {
      get { return gpsSettings_; }
      set {
        gpsSettings_ = value;
      }
    }

    /// <summary>Field number for the "festival_settings" field.</summary>
    public const int FestivalSettingsFieldNumber = 8;
    private global::POGOProtos.Settings.FestivalSettings festivalSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.FestivalSettings FestivalSettings {
      get { return festivalSettings_; }
      set {
        festivalSettings_ = value;
      }
    }

    /// <summary>Field number for the "event_settings" field.</summary>
    public const int EventSettingsFieldNumber = 9;
    private global::POGOProtos.Settings.EventSettings eventSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.EventSettings EventSettings {
      get { return eventSettings_; }
      set {
        eventSettings_ = value;
      }
    }

    /// <summary>Field number for the "max_pokemon_types" field.</summary>
    public const int MaxPokemonTypesFieldNumber = 10;
    private int maxPokemonTypes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxPokemonTypes {
      get { return maxPokemonTypes_; }
      set {
        maxPokemonTypes_ = value;
      }
    }

    /// <summary>Field number for the "sfida_settings" field.</summary>
    public const int SfidaSettingsFieldNumber = 11;
    private global::POGOProtos.Settings.SfidaSettings sfidaSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.SfidaSettings SfidaSettings {
      get { return sfidaSettings_; }
      set {
        sfidaSettings_ = value;
      }
    }

    /// <summary>Field number for the "news_settings" field.</summary>
    public const int NewsSettingsFieldNumber = 12;
    private global::POGOProtos.Settings.NewsSettings newsSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.NewsSettings NewsSettings {
      get { return newsSettings_; }
      set {
        newsSettings_ = value;
      }
    }

    /// <summary>Field number for the "translation_settings" field.</summary>
    public const int TranslationSettingsFieldNumber = 13;
    private global::POGOProtos.Settings.TranslationSettings translationSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.TranslationSettings TranslationSettings {
      get { return translationSettings_; }
      set {
        translationSettings_ = value;
      }
    }

    /// <summary>Field number for the "passcode_settings" field.</summary>
    public const int PasscodeSettingsFieldNumber = 14;
    private global::POGOProtos.Settings.PasscodeSettings passcodeSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.PasscodeSettings PasscodeSettings {
      get { return passcodeSettings_; }
      set {
        passcodeSettings_ = value;
      }
    }

    /// <summary>Field number for the "notification_settings" field.</summary>
    public const int NotificationSettingsFieldNumber = 15;
    private global::POGOProtos.Settings.NotificationSettings notificationSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.NotificationSettings NotificationSettings {
      get { return notificationSettings_; }
      set {
        notificationSettings_ = value;
      }
    }

    /// <summary>Field number for the "client_app_blacklist" field.</summary>
    public const int ClientAppBlacklistFieldNumber = 16;
    private static readonly pb::FieldCodec<string> _repeated_clientAppBlacklist_codec
        = pb::FieldCodec.ForString(130);
    private readonly pbc::RepeatedField<string> clientAppBlacklist_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ClientAppBlacklist {
      get { return clientAppBlacklist_; }
    }

    /// <summary>Field number for the "client_perf_settings" field.</summary>
    public const int ClientPerfSettingsFieldNumber = 17;
    private global::POGOProtos.Settings.ClientPerformanceSettings clientPerfSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.ClientPerformanceSettings ClientPerfSettings {
      get { return clientPerfSettings_; }
      set {
        clientPerfSettings_ = value;
      }
    }

    /// <summary>Field number for the "news_global_settings" field.</summary>
    public const int NewsGlobalSettingsFieldNumber = 18;
    private global::POGOProtos.Settings.NewsGlobalSettings newsGlobalSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.NewsGlobalSettings NewsGlobalSettings {
      get { return newsGlobalSettings_; }
      set {
        newsGlobalSettings_ = value;
      }
    }

    /// <summary>Field number for the "telemetry_global_settings" field.</summary>
    public const int TelemetryGlobalSettingsFieldNumber = 21;
    private global::POGOProtos.Settings.TelemetryGlobalSettings telemetryGlobalSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.TelemetryGlobalSettings TelemetryGlobalSettings {
      get { return telemetryGlobalSettings_; }
      set {
        telemetryGlobalSettings_ = value;
      }
    }

    /// <summary>Field number for the "login_settings" field.</summary>
    public const int LoginSettingsFieldNumber = 22;
    private global::POGOProtos.Settings.LoginSettings loginSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.LoginSettings LoginSettings {
      get { return loginSettings_; }
      set {
        loginSettings_ = value;
      }
    }

    /// <summary>Field number for the "quest_global_settings" field.</summary>
    public const int QuestGlobalSettingsFieldNumber = 19;
    private global::POGOProtos.Settings.QuestGlobalSettings questGlobalSettings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.QuestGlobalSettings QuestGlobalSettings {
      get { return questGlobalSettings_; }
      set {
        questGlobalSettings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GlobalSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GlobalSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FortSettings, other.FortSettings)) return false;
      if (!object.Equals(MapSettings, other.MapSettings)) return false;
      if (!object.Equals(LevelSettings, other.LevelSettings)) return false;
      if (!object.Equals(InventorySettings, other.InventorySettings)) return false;
      if (MinimumClientVersion != other.MinimumClientVersion) return false;
      if (!object.Equals(GpsSettings, other.GpsSettings)) return false;
      if (!object.Equals(FestivalSettings, other.FestivalSettings)) return false;
      if (!object.Equals(EventSettings, other.EventSettings)) return false;
      if (MaxPokemonTypes != other.MaxPokemonTypes) return false;
      if (!object.Equals(SfidaSettings, other.SfidaSettings)) return false;
      if (!object.Equals(NewsSettings, other.NewsSettings)) return false;
      if (!object.Equals(TranslationSettings, other.TranslationSettings)) return false;
      if (!object.Equals(PasscodeSettings, other.PasscodeSettings)) return false;
      if (!object.Equals(NotificationSettings, other.NotificationSettings)) return false;
      if(!clientAppBlacklist_.Equals(other.clientAppBlacklist_)) return false;
      if (!object.Equals(ClientPerfSettings, other.ClientPerfSettings)) return false;
      if (!object.Equals(NewsGlobalSettings, other.NewsGlobalSettings)) return false;
      if (!object.Equals(TelemetryGlobalSettings, other.TelemetryGlobalSettings)) return false;
      if (!object.Equals(LoginSettings, other.LoginSettings)) return false;
      if (!object.Equals(QuestGlobalSettings, other.QuestGlobalSettings)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (fortSettings_ != null) hash ^= FortSettings.GetHashCode();
      if (mapSettings_ != null) hash ^= MapSettings.GetHashCode();
      if (levelSettings_ != null) hash ^= LevelSettings.GetHashCode();
      if (inventorySettings_ != null) hash ^= InventorySettings.GetHashCode();
      if (MinimumClientVersion.Length != 0) hash ^= MinimumClientVersion.GetHashCode();
      if (gpsSettings_ != null) hash ^= GpsSettings.GetHashCode();
      if (festivalSettings_ != null) hash ^= FestivalSettings.GetHashCode();
      if (eventSettings_ != null) hash ^= EventSettings.GetHashCode();
      if (MaxPokemonTypes != 0) hash ^= MaxPokemonTypes.GetHashCode();
      if (sfidaSettings_ != null) hash ^= SfidaSettings.GetHashCode();
      if (newsSettings_ != null) hash ^= NewsSettings.GetHashCode();
      if (translationSettings_ != null) hash ^= TranslationSettings.GetHashCode();
      if (passcodeSettings_ != null) hash ^= PasscodeSettings.GetHashCode();
      if (notificationSettings_ != null) hash ^= NotificationSettings.GetHashCode();
      hash ^= clientAppBlacklist_.GetHashCode();
      if (clientPerfSettings_ != null) hash ^= ClientPerfSettings.GetHashCode();
      if (newsGlobalSettings_ != null) hash ^= NewsGlobalSettings.GetHashCode();
      if (telemetryGlobalSettings_ != null) hash ^= TelemetryGlobalSettings.GetHashCode();
      if (loginSettings_ != null) hash ^= LoginSettings.GetHashCode();
      if (questGlobalSettings_ != null) hash ^= QuestGlobalSettings.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (fortSettings_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FortSettings);
      }
      if (mapSettings_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MapSettings);
      }
      if (levelSettings_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LevelSettings);
      }
      if (inventorySettings_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(InventorySettings);
      }
      if (MinimumClientVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MinimumClientVersion);
      }
      if (gpsSettings_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(GpsSettings);
      }
      if (festivalSettings_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(FestivalSettings);
      }
      if (eventSettings_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(EventSettings);
      }
      if (MaxPokemonTypes != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(MaxPokemonTypes);
      }
      if (sfidaSettings_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(SfidaSettings);
      }
      if (newsSettings_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(NewsSettings);
      }
      if (translationSettings_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(TranslationSettings);
      }
      if (passcodeSettings_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(PasscodeSettings);
      }
      if (notificationSettings_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(NotificationSettings);
      }
      clientAppBlacklist_.WriteTo(output, _repeated_clientAppBlacklist_codec);
      if (clientPerfSettings_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(ClientPerfSettings);
      }
      if (newsGlobalSettings_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(NewsGlobalSettings);
      }
      if (questGlobalSettings_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(QuestGlobalSettings);
      }
      if (telemetryGlobalSettings_ != null) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(TelemetryGlobalSettings);
      }
      if (loginSettings_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(LoginSettings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (fortSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FortSettings);
      }
      if (mapSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapSettings);
      }
      if (levelSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LevelSettings);
      }
      if (inventorySettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InventorySettings);
      }
      if (MinimumClientVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MinimumClientVersion);
      }
      if (gpsSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GpsSettings);
      }
      if (festivalSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FestivalSettings);
      }
      if (eventSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EventSettings);
      }
      if (MaxPokemonTypes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxPokemonTypes);
      }
      if (sfidaSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SfidaSettings);
      }
      if (newsSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewsSettings);
      }
      if (translationSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TranslationSettings);
      }
      if (passcodeSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PasscodeSettings);
      }
      if (notificationSettings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NotificationSettings);
      }
      size += clientAppBlacklist_.CalculateSize(_repeated_clientAppBlacklist_codec);
      if (clientPerfSettings_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ClientPerfSettings);
      }
      if (newsGlobalSettings_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(NewsGlobalSettings);
      }
      if (telemetryGlobalSettings_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(TelemetryGlobalSettings);
      }
      if (loginSettings_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LoginSettings);
      }
      if (questGlobalSettings_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(QuestGlobalSettings);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GlobalSettings other) {
      if (other == null) {
        return;
      }
      if (other.fortSettings_ != null) {
        if (fortSettings_ == null) {
          fortSettings_ = new global::POGOProtos.Settings.FortSettings();
        }
        FortSettings.MergeFrom(other.FortSettings);
      }
      if (other.mapSettings_ != null) {
        if (mapSettings_ == null) {
          mapSettings_ = new global::POGOProtos.Settings.MapSettings();
        }
        MapSettings.MergeFrom(other.MapSettings);
      }
      if (other.levelSettings_ != null) {
        if (levelSettings_ == null) {
          levelSettings_ = new global::POGOProtos.Settings.LevelSettings();
        }
        LevelSettings.MergeFrom(other.LevelSettings);
      }
      if (other.inventorySettings_ != null) {
        if (inventorySettings_ == null) {
          inventorySettings_ = new global::POGOProtos.Settings.InventorySettings();
        }
        InventorySettings.MergeFrom(other.InventorySettings);
      }
      if (other.MinimumClientVersion.Length != 0) {
        MinimumClientVersion = other.MinimumClientVersion;
      }
      if (other.gpsSettings_ != null) {
        if (gpsSettings_ == null) {
          gpsSettings_ = new global::POGOProtos.Settings.GpsSettings();
        }
        GpsSettings.MergeFrom(other.GpsSettings);
      }
      if (other.festivalSettings_ != null) {
        if (festivalSettings_ == null) {
          festivalSettings_ = new global::POGOProtos.Settings.FestivalSettings();
        }
        FestivalSettings.MergeFrom(other.FestivalSettings);
      }
      if (other.eventSettings_ != null) {
        if (eventSettings_ == null) {
          eventSettings_ = new global::POGOProtos.Settings.EventSettings();
        }
        EventSettings.MergeFrom(other.EventSettings);
      }
      if (other.MaxPokemonTypes != 0) {
        MaxPokemonTypes = other.MaxPokemonTypes;
      }
      if (other.sfidaSettings_ != null) {
        if (sfidaSettings_ == null) {
          sfidaSettings_ = new global::POGOProtos.Settings.SfidaSettings();
        }
        SfidaSettings.MergeFrom(other.SfidaSettings);
      }
      if (other.newsSettings_ != null) {
        if (newsSettings_ == null) {
          newsSettings_ = new global::POGOProtos.Settings.NewsSettings();
        }
        NewsSettings.MergeFrom(other.NewsSettings);
      }
      if (other.translationSettings_ != null) {
        if (translationSettings_ == null) {
          translationSettings_ = new global::POGOProtos.Settings.TranslationSettings();
        }
        TranslationSettings.MergeFrom(other.TranslationSettings);
      }
      if (other.passcodeSettings_ != null) {
        if (passcodeSettings_ == null) {
          passcodeSettings_ = new global::POGOProtos.Settings.PasscodeSettings();
        }
        PasscodeSettings.MergeFrom(other.PasscodeSettings);
      }
      if (other.notificationSettings_ != null) {
        if (notificationSettings_ == null) {
          notificationSettings_ = new global::POGOProtos.Settings.NotificationSettings();
        }
        NotificationSettings.MergeFrom(other.NotificationSettings);
      }
      clientAppBlacklist_.Add(other.clientAppBlacklist_);
      if (other.clientPerfSettings_ != null) {
        if (clientPerfSettings_ == null) {
          clientPerfSettings_ = new global::POGOProtos.Settings.ClientPerformanceSettings();
        }
        ClientPerfSettings.MergeFrom(other.ClientPerfSettings);
      }
      if (other.newsGlobalSettings_ != null) {
        if (newsGlobalSettings_ == null) {
          newsGlobalSettings_ = new global::POGOProtos.Settings.NewsGlobalSettings();
        }
        NewsGlobalSettings.MergeFrom(other.NewsGlobalSettings);
      }
      if (other.telemetryGlobalSettings_ != null) {
        if (telemetryGlobalSettings_ == null) {
          telemetryGlobalSettings_ = new global::POGOProtos.Settings.TelemetryGlobalSettings();
        }
        TelemetryGlobalSettings.MergeFrom(other.TelemetryGlobalSettings);
      }
      if (other.loginSettings_ != null) {
        if (loginSettings_ == null) {
          loginSettings_ = new global::POGOProtos.Settings.LoginSettings();
        }
        LoginSettings.MergeFrom(other.LoginSettings);
      }
      if (other.questGlobalSettings_ != null) {
        if (questGlobalSettings_ == null) {
          questGlobalSettings_ = new global::POGOProtos.Settings.QuestGlobalSettings();
        }
        QuestGlobalSettings.MergeFrom(other.QuestGlobalSettings);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (fortSettings_ == null) {
              fortSettings_ = new global::POGOProtos.Settings.FortSettings();
            }
            input.ReadMessage(fortSettings_);
            break;
          }
          case 26: {
            if (mapSettings_ == null) {
              mapSettings_ = new global::POGOProtos.Settings.MapSettings();
            }
            input.ReadMessage(mapSettings_);
            break;
          }
          case 34: {
            if (levelSettings_ == null) {
              levelSettings_ = new global::POGOProtos.Settings.LevelSettings();
            }
            input.ReadMessage(levelSettings_);
            break;
          }
          case 42: {
            if (inventorySettings_ == null) {
              inventorySettings_ = new global::POGOProtos.Settings.InventorySettings();
            }
            input.ReadMessage(inventorySettings_);
            break;
          }
          case 50: {
            MinimumClientVersion = input.ReadString();
            break;
          }
          case 58: {
            if (gpsSettings_ == null) {
              gpsSettings_ = new global::POGOProtos.Settings.GpsSettings();
            }
            input.ReadMessage(gpsSettings_);
            break;
          }
          case 66: {
            if (festivalSettings_ == null) {
              festivalSettings_ = new global::POGOProtos.Settings.FestivalSettings();
            }
            input.ReadMessage(festivalSettings_);
            break;
          }
          case 74: {
            if (eventSettings_ == null) {
              eventSettings_ = new global::POGOProtos.Settings.EventSettings();
            }
            input.ReadMessage(eventSettings_);
            break;
          }
          case 80: {
            MaxPokemonTypes = input.ReadInt32();
            break;
          }
          case 90: {
            if (sfidaSettings_ == null) {
              sfidaSettings_ = new global::POGOProtos.Settings.SfidaSettings();
            }
            input.ReadMessage(sfidaSettings_);
            break;
          }
          case 98: {
            if (newsSettings_ == null) {
              newsSettings_ = new global::POGOProtos.Settings.NewsSettings();
            }
            input.ReadMessage(newsSettings_);
            break;
          }
          case 106: {
            if (translationSettings_ == null) {
              translationSettings_ = new global::POGOProtos.Settings.TranslationSettings();
            }
            input.ReadMessage(translationSettings_);
            break;
          }
          case 114: {
            if (passcodeSettings_ == null) {
              passcodeSettings_ = new global::POGOProtos.Settings.PasscodeSettings();
            }
            input.ReadMessage(passcodeSettings_);
            break;
          }
          case 122: {
            if (notificationSettings_ == null) {
              notificationSettings_ = new global::POGOProtos.Settings.NotificationSettings();
            }
            input.ReadMessage(notificationSettings_);
            break;
          }
          case 130: {
            clientAppBlacklist_.AddEntriesFrom(input, _repeated_clientAppBlacklist_codec);
            break;
          }
          case 138: {
            if (clientPerfSettings_ == null) {
              clientPerfSettings_ = new global::POGOProtos.Settings.ClientPerformanceSettings();
            }
            input.ReadMessage(clientPerfSettings_);
            break;
          }
          case 146: {
            if (newsGlobalSettings_ == null) {
              newsGlobalSettings_ = new global::POGOProtos.Settings.NewsGlobalSettings();
            }
            input.ReadMessage(newsGlobalSettings_);
            break;
          }
          case 154: {
            if (questGlobalSettings_ == null) {
              questGlobalSettings_ = new global::POGOProtos.Settings.QuestGlobalSettings();
            }
            input.ReadMessage(questGlobalSettings_);
            break;
          }
          case 170: {
            if (telemetryGlobalSettings_ == null) {
              telemetryGlobalSettings_ = new global::POGOProtos.Settings.TelemetryGlobalSettings();
            }
            input.ReadMessage(telemetryGlobalSettings_);
            break;
          }
          case 178: {
            if (loginSettings_ == null) {
              loginSettings_ = new global::POGOProtos.Settings.LoginSettings();
            }
            input.ReadMessage(loginSettings_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
