// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Settings/MapSettings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/MapSettings.proto</summary>
  public static partial class MapSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/MapSettings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MapSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVQT0dPUHJvdG9zL1NldHRpbmdzL01hcFNldHRpbmdzLnByb3RvEhNQT0dP",
            "UHJvdG9zLlNldHRpbmdzIvcCCgtNYXBTZXR0aW5ncxIdChVwb2tlbW9uX3Zp",
            "c2libGVfcmFuZ2UYASABKAESHQoVcG9rZV9uYXZfcmFuZ2VfbWV0ZXJzGAIg",
            "ASgBEh4KFmVuY291bnRlcl9yYW5nZV9tZXRlcnMYAyABKAESKwojZ2V0X21h",
            "cF9vYmplY3RzX21pbl9yZWZyZXNoX3NlY29uZHMYBCABKAISKwojZ2V0X21h",
            "cF9vYmplY3RzX21heF9yZWZyZXNoX3NlY29uZHMYBSABKAISKwojZ2V0X21h",
            "cF9vYmplY3RzX21pbl9kaXN0YW5jZV9tZXRlcnMYBiABKAISGwoTZ29vZ2xl",
            "X21hcHNfYXBpX2tleRgHIAEoCRIhChltaW5fbmVhcmJ5X2hpZGVfc2lnaHRp",
            "bmdzGAggASgFEh4KFmVuYWJsZV9zcGVjaWFsX3dlYXRoZXIYCSABKAgSIwob",
            "c3BlY2lhbF93ZWF0aGVyX3Byb2JhYmlsaXR5GAogASgCYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.MapSettings), global::POGOProtos.Settings.MapSettings.Parser, new[]{ "PokemonVisibleRange", "PokeNavRangeMeters", "EncounterRangeMeters", "GetMapObjectsMinRefreshSeconds", "GetMapObjectsMaxRefreshSeconds", "GetMapObjectsMinDistanceMeters", "GoogleMapsApiKey", "MinNearbyHideSightings", "EnableSpecialWeather", "SpecialWeatherProbability" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MapSettings : pb::IMessage<MapSettings> {
    private static readonly pb::MessageParser<MapSettings> _parser = new pb::MessageParser<MapSettings>(() => new MapSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MapSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.MapSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapSettings(MapSettings other) : this() {
      pokemonVisibleRange_ = other.pokemonVisibleRange_;
      pokeNavRangeMeters_ = other.pokeNavRangeMeters_;
      encounterRangeMeters_ = other.encounterRangeMeters_;
      getMapObjectsMinRefreshSeconds_ = other.getMapObjectsMinRefreshSeconds_;
      getMapObjectsMaxRefreshSeconds_ = other.getMapObjectsMaxRefreshSeconds_;
      getMapObjectsMinDistanceMeters_ = other.getMapObjectsMinDistanceMeters_;
      googleMapsApiKey_ = other.googleMapsApiKey_;
      minNearbyHideSightings_ = other.minNearbyHideSightings_;
      enableSpecialWeather_ = other.enableSpecialWeather_;
      specialWeatherProbability_ = other.specialWeatherProbability_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MapSettings Clone() {
      return new MapSettings(this);
    }

    /// <summary>Field number for the "pokemon_visible_range" field.</summary>
    public const int PokemonVisibleRangeFieldNumber = 1;
    private double pokemonVisibleRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double PokemonVisibleRange {
      get { return pokemonVisibleRange_; }
      set {
        pokemonVisibleRange_ = value;
      }
    }

    /// <summary>Field number for the "poke_nav_range_meters" field.</summary>
    public const int PokeNavRangeMetersFieldNumber = 2;
    private double pokeNavRangeMeters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double PokeNavRangeMeters {
      get { return pokeNavRangeMeters_; }
      set {
        pokeNavRangeMeters_ = value;
      }
    }

    /// <summary>Field number for the "encounter_range_meters" field.</summary>
    public const int EncounterRangeMetersFieldNumber = 3;
    private double encounterRangeMeters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double EncounterRangeMeters {
      get { return encounterRangeMeters_; }
      set {
        encounterRangeMeters_ = value;
      }
    }

    /// <summary>Field number for the "get_map_objects_min_refresh_seconds" field.</summary>
    public const int GetMapObjectsMinRefreshSecondsFieldNumber = 4;
    private float getMapObjectsMinRefreshSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float GetMapObjectsMinRefreshSeconds {
      get { return getMapObjectsMinRefreshSeconds_; }
      set {
        getMapObjectsMinRefreshSeconds_ = value;
      }
    }

    /// <summary>Field number for the "get_map_objects_max_refresh_seconds" field.</summary>
    public const int GetMapObjectsMaxRefreshSecondsFieldNumber = 5;
    private float getMapObjectsMaxRefreshSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float GetMapObjectsMaxRefreshSeconds {
      get { return getMapObjectsMaxRefreshSeconds_; }
      set {
        getMapObjectsMaxRefreshSeconds_ = value;
      }
    }

    /// <summary>Field number for the "get_map_objects_min_distance_meters" field.</summary>
    public const int GetMapObjectsMinDistanceMetersFieldNumber = 6;
    private float getMapObjectsMinDistanceMeters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float GetMapObjectsMinDistanceMeters {
      get { return getMapObjectsMinDistanceMeters_; }
      set {
        getMapObjectsMinDistanceMeters_ = value;
      }
    }

    /// <summary>Field number for the "google_maps_api_key" field.</summary>
    public const int GoogleMapsApiKeyFieldNumber = 7;
    private string googleMapsApiKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GoogleMapsApiKey {
      get { return googleMapsApiKey_; }
      set {
        googleMapsApiKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "min_nearby_hide_sightings" field.</summary>
    public const int MinNearbyHideSightingsFieldNumber = 8;
    private int minNearbyHideSightings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MinNearbyHideSightings {
      get { return minNearbyHideSightings_; }
      set {
        minNearbyHideSightings_ = value;
      }
    }

    /// <summary>Field number for the "enable_special_weather" field.</summary>
    public const int EnableSpecialWeatherFieldNumber = 9;
    private bool enableSpecialWeather_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EnableSpecialWeather {
      get { return enableSpecialWeather_; }
      set {
        enableSpecialWeather_ = value;
      }
    }

    /// <summary>Field number for the "special_weather_probability" field.</summary>
    public const int SpecialWeatherProbabilityFieldNumber = 10;
    private float specialWeatherProbability_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float SpecialWeatherProbability {
      get { return specialWeatherProbability_; }
      set {
        specialWeatherProbability_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MapSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MapSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PokemonVisibleRange, other.PokemonVisibleRange)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PokeNavRangeMeters, other.PokeNavRangeMeters)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(EncounterRangeMeters, other.EncounterRangeMeters)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(GetMapObjectsMinRefreshSeconds, other.GetMapObjectsMinRefreshSeconds)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(GetMapObjectsMaxRefreshSeconds, other.GetMapObjectsMaxRefreshSeconds)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(GetMapObjectsMinDistanceMeters, other.GetMapObjectsMinDistanceMeters)) return false;
      if (GoogleMapsApiKey != other.GoogleMapsApiKey) return false;
      if (MinNearbyHideSightings != other.MinNearbyHideSightings) return false;
      if (EnableSpecialWeather != other.EnableSpecialWeather) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SpecialWeatherProbability, other.SpecialWeatherProbability)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PokemonVisibleRange != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PokemonVisibleRange);
      if (PokeNavRangeMeters != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PokeNavRangeMeters);
      if (EncounterRangeMeters != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(EncounterRangeMeters);
      if (GetMapObjectsMinRefreshSeconds != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(GetMapObjectsMinRefreshSeconds);
      if (GetMapObjectsMaxRefreshSeconds != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(GetMapObjectsMaxRefreshSeconds);
      if (GetMapObjectsMinDistanceMeters != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(GetMapObjectsMinDistanceMeters);
      if (GoogleMapsApiKey.Length != 0) hash ^= GoogleMapsApiKey.GetHashCode();
      if (MinNearbyHideSightings != 0) hash ^= MinNearbyHideSightings.GetHashCode();
      if (EnableSpecialWeather != false) hash ^= EnableSpecialWeather.GetHashCode();
      if (SpecialWeatherProbability != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SpecialWeatherProbability);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PokemonVisibleRange != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(PokemonVisibleRange);
      }
      if (PokeNavRangeMeters != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(PokeNavRangeMeters);
      }
      if (EncounterRangeMeters != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(EncounterRangeMeters);
      }
      if (GetMapObjectsMinRefreshSeconds != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(GetMapObjectsMinRefreshSeconds);
      }
      if (GetMapObjectsMaxRefreshSeconds != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(GetMapObjectsMaxRefreshSeconds);
      }
      if (GetMapObjectsMinDistanceMeters != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(GetMapObjectsMinDistanceMeters);
      }
      if (GoogleMapsApiKey.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(GoogleMapsApiKey);
      }
      if (MinNearbyHideSightings != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MinNearbyHideSightings);
      }
      if (EnableSpecialWeather != false) {
        output.WriteRawTag(72);
        output.WriteBool(EnableSpecialWeather);
      }
      if (SpecialWeatherProbability != 0F) {
        output.WriteRawTag(85);
        output.WriteFloat(SpecialWeatherProbability);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PokemonVisibleRange != 0D) {
        size += 1 + 8;
      }
      if (PokeNavRangeMeters != 0D) {
        size += 1 + 8;
      }
      if (EncounterRangeMeters != 0D) {
        size += 1 + 8;
      }
      if (GetMapObjectsMinRefreshSeconds != 0F) {
        size += 1 + 4;
      }
      if (GetMapObjectsMaxRefreshSeconds != 0F) {
        size += 1 + 4;
      }
      if (GetMapObjectsMinDistanceMeters != 0F) {
        size += 1 + 4;
      }
      if (GoogleMapsApiKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GoogleMapsApiKey);
      }
      if (MinNearbyHideSightings != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MinNearbyHideSightings);
      }
      if (EnableSpecialWeather != false) {
        size += 1 + 1;
      }
      if (SpecialWeatherProbability != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MapSettings other) {
      if (other == null) {
        return;
      }
      if (other.PokemonVisibleRange != 0D) {
        PokemonVisibleRange = other.PokemonVisibleRange;
      }
      if (other.PokeNavRangeMeters != 0D) {
        PokeNavRangeMeters = other.PokeNavRangeMeters;
      }
      if (other.EncounterRangeMeters != 0D) {
        EncounterRangeMeters = other.EncounterRangeMeters;
      }
      if (other.GetMapObjectsMinRefreshSeconds != 0F) {
        GetMapObjectsMinRefreshSeconds = other.GetMapObjectsMinRefreshSeconds;
      }
      if (other.GetMapObjectsMaxRefreshSeconds != 0F) {
        GetMapObjectsMaxRefreshSeconds = other.GetMapObjectsMaxRefreshSeconds;
      }
      if (other.GetMapObjectsMinDistanceMeters != 0F) {
        GetMapObjectsMinDistanceMeters = other.GetMapObjectsMinDistanceMeters;
      }
      if (other.GoogleMapsApiKey.Length != 0) {
        GoogleMapsApiKey = other.GoogleMapsApiKey;
      }
      if (other.MinNearbyHideSightings != 0) {
        MinNearbyHideSightings = other.MinNearbyHideSightings;
      }
      if (other.EnableSpecialWeather != false) {
        EnableSpecialWeather = other.EnableSpecialWeather;
      }
      if (other.SpecialWeatherProbability != 0F) {
        SpecialWeatherProbability = other.SpecialWeatherProbability;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            PokemonVisibleRange = input.ReadDouble();
            break;
          }
          case 17: {
            PokeNavRangeMeters = input.ReadDouble();
            break;
          }
          case 25: {
            EncounterRangeMeters = input.ReadDouble();
            break;
          }
          case 37: {
            GetMapObjectsMinRefreshSeconds = input.ReadFloat();
            break;
          }
          case 45: {
            GetMapObjectsMaxRefreshSeconds = input.ReadFloat();
            break;
          }
          case 53: {
            GetMapObjectsMinDistanceMeters = input.ReadFloat();
            break;
          }
          case 58: {
            GoogleMapsApiKey = input.ReadString();
            break;
          }
          case 64: {
            MinNearbyHideSightings = input.ReadInt32();
            break;
          }
          case 72: {
            EnableSpecialWeather = input.ReadBool();
            break;
          }
          case 85: {
            SpecialWeatherProbability = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
