// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Settings/SocialPlayerSettings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/SocialPlayerSettings.proto</summary>
  public static partial class SocialPlayerSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/SocialPlayerSettings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SocialPlayerSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5QT0dPUHJvdG9zL1NldHRpbmdzL1NvY2lhbFBsYXllclNldHRpbmdzLnBy",
            "b3RvEhNQT0dPUHJvdG9zLlNldHRpbmdzIjsKFFNvY2lhbFBsYXllclNldHRp",
            "bmdzEiMKG2Rpc2FibGVfbGFzdF9wb2tlbW9uX2NhdWdodBgBIAEoCGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.SocialPlayerSettings), global::POGOProtos.Settings.SocialPlayerSettings.Parser, new[]{ "DisableLastPokemonCaught" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SocialPlayerSettings : pb::IMessage<SocialPlayerSettings> {
    private static readonly pb::MessageParser<SocialPlayerSettings> _parser = new pb::MessageParser<SocialPlayerSettings>(() => new SocialPlayerSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SocialPlayerSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.SocialPlayerSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocialPlayerSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocialPlayerSettings(SocialPlayerSettings other) : this() {
      disableLastPokemonCaught_ = other.disableLastPokemonCaught_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocialPlayerSettings Clone() {
      return new SocialPlayerSettings(this);
    }

    /// <summary>Field number for the "disable_last_pokemon_caught" field.</summary>
    public const int DisableLastPokemonCaughtFieldNumber = 1;
    private bool disableLastPokemonCaught_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool DisableLastPokemonCaught {
      get { return disableLastPokemonCaught_; }
      set {
        disableLastPokemonCaught_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SocialPlayerSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SocialPlayerSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DisableLastPokemonCaught != other.DisableLastPokemonCaught) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DisableLastPokemonCaught != false) hash ^= DisableLastPokemonCaught.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DisableLastPokemonCaught != false) {
        output.WriteRawTag(8);
        output.WriteBool(DisableLastPokemonCaught);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DisableLastPokemonCaught != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SocialPlayerSettings other) {
      if (other == null) {
        return;
      }
      if (other.DisableLastPokemonCaught != false) {
        DisableLastPokemonCaught = other.DisableLastPokemonCaught;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DisableLastPokemonCaught = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
