// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Settings/SocialClientSettings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/SocialClientSettings.proto</summary>
  public static partial class SocialClientSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/SocialClientSettings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SocialClientSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5QT0dPUHJvdG9zL1NldHRpbmdzL1NvY2lhbENsaWVudFNldHRpbmdzLnBy",
            "b3RvEhNQT0dPUHJvdG9zLlNldHRpbmdzImQKFFNvY2lhbENsaWVudFNldHRp",
            "bmdzEhUKDWVuYWJsZV9zb2NpYWwYASABKAgSGgoSbWF4X2ZyaWVuZF9kZXRh",
            "aWxzGAIgASgFEhkKEXBsYXllcl9sZXZlbF9nYXRlGAMgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.SocialClientSettings), global::POGOProtos.Settings.SocialClientSettings.Parser, new[]{ "EnableSocial", "MaxFriendDetails", "PlayerLevelGate" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SocialClientSettings : pb::IMessage<SocialClientSettings> {
    private static readonly pb::MessageParser<SocialClientSettings> _parser = new pb::MessageParser<SocialClientSettings>(() => new SocialClientSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SocialClientSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.SocialClientSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocialClientSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocialClientSettings(SocialClientSettings other) : this() {
      enableSocial_ = other.enableSocial_;
      maxFriendDetails_ = other.maxFriendDetails_;
      playerLevelGate_ = other.playerLevelGate_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocialClientSettings Clone() {
      return new SocialClientSettings(this);
    }

    /// <summary>Field number for the "enable_social" field.</summary>
    public const int EnableSocialFieldNumber = 1;
    private bool enableSocial_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EnableSocial {
      get { return enableSocial_; }
      set {
        enableSocial_ = value;
      }
    }

    /// <summary>Field number for the "max_friend_details" field.</summary>
    public const int MaxFriendDetailsFieldNumber = 2;
    private int maxFriendDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxFriendDetails {
      get { return maxFriendDetails_; }
      set {
        maxFriendDetails_ = value;
      }
    }

    /// <summary>Field number for the "player_level_gate" field.</summary>
    public const int PlayerLevelGateFieldNumber = 3;
    private int playerLevelGate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PlayerLevelGate {
      get { return playerLevelGate_; }
      set {
        playerLevelGate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SocialClientSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SocialClientSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnableSocial != other.EnableSocial) return false;
      if (MaxFriendDetails != other.MaxFriendDetails) return false;
      if (PlayerLevelGate != other.PlayerLevelGate) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EnableSocial != false) hash ^= EnableSocial.GetHashCode();
      if (MaxFriendDetails != 0) hash ^= MaxFriendDetails.GetHashCode();
      if (PlayerLevelGate != 0) hash ^= PlayerLevelGate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EnableSocial != false) {
        output.WriteRawTag(8);
        output.WriteBool(EnableSocial);
      }
      if (MaxFriendDetails != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MaxFriendDetails);
      }
      if (PlayerLevelGate != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PlayerLevelGate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EnableSocial != false) {
        size += 1 + 1;
      }
      if (MaxFriendDetails != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxFriendDetails);
      }
      if (PlayerLevelGate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerLevelGate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SocialClientSettings other) {
      if (other == null) {
        return;
      }
      if (other.EnableSocial != false) {
        EnableSocial = other.EnableSocial;
      }
      if (other.MaxFriendDetails != 0) {
        MaxFriendDetails = other.MaxFriendDetails;
      }
      if (other.PlayerLevelGate != 0) {
        PlayerLevelGate = other.PlayerLevelGate;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EnableSocial = input.ReadBool();
            break;
          }
          case 16: {
            MaxFriendDetails = input.ReadInt32();
            break;
          }
          case 24: {
            PlayerLevelGate = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
