// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Networking/Responses/Social/GetFriendDetailsResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses.Social {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/Social/GetFriendDetailsResponse.proto</summary>
  public static partial class GetFriendDetailsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/Social/GetFriendDetailsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetFriendDetailsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkVQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL1NvY2lhbC9HZXRG",
            "cmllbmREZXRhaWxzUmVzcG9uc2UucHJvdG8SJlBPR09Qcm90b3MuTmV0d29y",
            "a2luZy5SZXNwb25zZXMuU29jaWFsGitQT0dPUHJvdG9zL0RhdGEvRnJpZW5k",
            "cy9GcmllbmREZXRhaWxzLnByb3RvIswFChhHZXRGcmllbmREZXRhaWxzUmVz",
            "cG9uc2USVwoGcmVzdWx0GAEgASgOMkcuUE9HT1Byb3Rvcy5OZXR3b3JraW5n",
            "LlJlc3BvbnNlcy5Tb2NpYWwuR2V0RnJpZW5kRGV0YWlsc1Jlc3BvbnNlLlJl",
            "c3VsdBI2CgZmcmllbmQYAiADKAsyJi5QT0dPUHJvdG9zLkRhdGEuRnJpZW5k",
            "cy5GcmllbmREZXRhaWxzEmkKGWZyaWVuZF9kZXRhaWxzX2RlYnVnX2luZm8Y",
            "AyABKAsyRi5QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9uc2VzLlNvY2lh",
            "bC5HZXRGcmllbmREZXRhaWxzUmVzcG9uc2UuRGVidWcaLgoGQ2FsbGVlEhEK",
            "CWNhbGxlZV9pZBgBIAMoBRIRCglwbGF5ZXJfaWQYAiABKAkaqwIKBURlYnVn",
            "EhcKD2ZldGNoZWRfZnJvbV9kYhgBIAEoBRIbChNmZXRjaGVkX2Zyb21fZmFu",
            "b3V0GAIgASgFEiIKGmZldGNoZWRfZnJvbV9wbGF5ZXJfbWFwcGVyGAMgASgF",
            "EiEKGWZldGNoZWRfZnJvbV9zdGF0dXNfY2FjaGUYBCABKAUSFwoPZmFpbGVk",
            "X3RvX2ZldGNoGAUgASgFElwKC2NhbGxlZV9saXN0GAYgAygLMkcuUE9HT1By",
            "b3Rvcy5OZXR3b3JraW5nLlJlc3BvbnNlcy5Tb2NpYWwuR2V0RnJpZW5kRGV0",
            "YWlsc1Jlc3BvbnNlLkNhbGxlZRouCgZDYWxsZWUSEQoJY2FsbGVlX2lkGAEg",
            "AygFEhEKCXBsYXllcl9pZBgCIAEoCSJWCgZSZXN1bHQSCQoFVU5TRVQQABIL",
            "CgdTVUNDRVNTEAESEQoNRVJST1JfVU5LTk9XThACEiEKHUVYQ0VFRFNfTUFY",
            "X1BMQVlFUlNfUEVSX1FVRVJZEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Friends.FriendDetailsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse), global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Parser, new[]{ "Result", "Friend", "FriendDetailsDebugInfo" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Result) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Callee), global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Callee.Parser, new[]{ "CalleeId", "PlayerId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug), global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug.Parser, new[]{ "FetchedFromDb", "FetchedFromFanout", "FetchedFromPlayerMapper", "FetchedFromStatusCache", "FailedToFetch", "CalleeList" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug.Types.Callee), global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug.Types.Callee.Parser, new[]{ "CalleeId", "PlayerId" }, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetFriendDetailsResponse : pb::IMessage<GetFriendDetailsResponse> {
    private static readonly pb::MessageParser<GetFriendDetailsResponse> _parser = new pb::MessageParser<GetFriendDetailsResponse>(() => new GetFriendDetailsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetFriendDetailsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFriendDetailsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFriendDetailsResponse(GetFriendDetailsResponse other) : this() {
      result_ = other.result_;
      friend_ = other.friend_.Clone();
      friendDetailsDebugInfo_ = other.friendDetailsDebugInfo_ != null ? other.friendDetailsDebugInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFriendDetailsResponse Clone() {
      return new GetFriendDetailsResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "friend" field.</summary>
    public const int FriendFieldNumber = 2;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Friends.FriendDetails> _repeated_friend_codec
        = pb::FieldCodec.ForMessage(18, global::POGOProtos.Data.Friends.FriendDetails.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Friends.FriendDetails> friend_ = new pbc::RepeatedField<global::POGOProtos.Data.Friends.FriendDetails>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Friends.FriendDetails> Friend {
      get { return friend_; }
    }

    /// <summary>Field number for the "friend_details_debug_info" field.</summary>
    public const int FriendDetailsDebugInfoFieldNumber = 3;
    private global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug friendDetailsDebugInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug FriendDetailsDebugInfo {
      get { return friendDetailsDebugInfo_; }
      set {
        friendDetailsDebugInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetFriendDetailsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetFriendDetailsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!friend_.Equals(other.friend_)) return false;
      if (!object.Equals(FriendDetailsDebugInfo, other.FriendDetailsDebugInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      hash ^= friend_.GetHashCode();
      if (friendDetailsDebugInfo_ != null) hash ^= FriendDetailsDebugInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      friend_.WriteTo(output, _repeated_friend_codec);
      if (friendDetailsDebugInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FriendDetailsDebugInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      size += friend_.CalculateSize(_repeated_friend_codec);
      if (friendDetailsDebugInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FriendDetailsDebugInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetFriendDetailsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      friend_.Add(other.friend_);
      if (other.friendDetailsDebugInfo_ != null) {
        if (friendDetailsDebugInfo_ == null) {
          friendDetailsDebugInfo_ = new global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug();
        }
        FriendDetailsDebugInfo.MergeFrom(other.FriendDetailsDebugInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            friend_.AddEntriesFrom(input, _repeated_friend_codec);
            break;
          }
          case 26: {
            if (friendDetailsDebugInfo_ == null) {
              friendDetailsDebugInfo_ = new global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug();
            }
            input.ReadMessage(friendDetailsDebugInfo_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GetFriendDetailsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_UNKNOWN")] ErrorUnknown = 2,
        [pbr::OriginalName("EXCEEDS_MAX_PLAYERS_PER_QUERY")] ExceedsMaxPlayersPerQuery = 3,
      }

      public sealed partial class Callee : pb::IMessage<Callee> {
        private static readonly pb::MessageParser<Callee> _parser = new pb::MessageParser<Callee>(() => new Callee());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Callee> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Callee() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Callee(Callee other) : this() {
          calleeId_ = other.calleeId_.Clone();
          playerId_ = other.playerId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Callee Clone() {
          return new Callee(this);
        }

        /// <summary>Field number for the "callee_id" field.</summary>
        public const int CalleeIdFieldNumber = 1;
        private static readonly pb::FieldCodec<int> _repeated_calleeId_codec
            = pb::FieldCodec.ForInt32(10);
        private readonly pbc::RepeatedField<int> calleeId_ = new pbc::RepeatedField<int>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<int> CalleeId {
          get { return calleeId_; }
        }

        /// <summary>Field number for the "player_id" field.</summary>
        public const int PlayerIdFieldNumber = 2;
        private string playerId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string PlayerId {
          get { return playerId_; }
          set {
            playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Callee);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Callee other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!calleeId_.Equals(other.calleeId_)) return false;
          if (PlayerId != other.PlayerId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= calleeId_.GetHashCode();
          if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          calleeId_.WriteTo(output, _repeated_calleeId_codec);
          if (PlayerId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(PlayerId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          size += calleeId_.CalculateSize(_repeated_calleeId_codec);
          if (PlayerId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Callee other) {
          if (other == null) {
            return;
          }
          calleeId_.Add(other.calleeId_);
          if (other.PlayerId.Length != 0) {
            PlayerId = other.PlayerId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10:
              case 8: {
                calleeId_.AddEntriesFrom(input, _repeated_calleeId_codec);
                break;
              }
              case 18: {
                PlayerId = input.ReadString();
                break;
              }
            }
          }
        }

      }

      public sealed partial class Debug : pb::IMessage<Debug> {
        private static readonly pb::MessageParser<Debug> _parser = new pb::MessageParser<Debug>(() => new Debug());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Debug> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Debug() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Debug(Debug other) : this() {
          fetchedFromDb_ = other.fetchedFromDb_;
          fetchedFromFanout_ = other.fetchedFromFanout_;
          fetchedFromPlayerMapper_ = other.fetchedFromPlayerMapper_;
          fetchedFromStatusCache_ = other.fetchedFromStatusCache_;
          failedToFetch_ = other.failedToFetch_;
          calleeList_ = other.calleeList_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Debug Clone() {
          return new Debug(this);
        }

        /// <summary>Field number for the "fetched_from_db" field.</summary>
        public const int FetchedFromDbFieldNumber = 1;
        private int fetchedFromDb_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int FetchedFromDb {
          get { return fetchedFromDb_; }
          set {
            fetchedFromDb_ = value;
          }
        }

        /// <summary>Field number for the "fetched_from_fanout" field.</summary>
        public const int FetchedFromFanoutFieldNumber = 2;
        private int fetchedFromFanout_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int FetchedFromFanout {
          get { return fetchedFromFanout_; }
          set {
            fetchedFromFanout_ = value;
          }
        }

        /// <summary>Field number for the "fetched_from_player_mapper" field.</summary>
        public const int FetchedFromPlayerMapperFieldNumber = 3;
        private int fetchedFromPlayerMapper_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int FetchedFromPlayerMapper {
          get { return fetchedFromPlayerMapper_; }
          set {
            fetchedFromPlayerMapper_ = value;
          }
        }

        /// <summary>Field number for the "fetched_from_status_cache" field.</summary>
        public const int FetchedFromStatusCacheFieldNumber = 4;
        private int fetchedFromStatusCache_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int FetchedFromStatusCache {
          get { return fetchedFromStatusCache_; }
          set {
            fetchedFromStatusCache_ = value;
          }
        }

        /// <summary>Field number for the "failed_to_fetch" field.</summary>
        public const int FailedToFetchFieldNumber = 5;
        private int failedToFetch_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int FailedToFetch {
          get { return failedToFetch_; }
          set {
            failedToFetch_ = value;
          }
        }

        /// <summary>Field number for the "callee_list" field.</summary>
        public const int CalleeListFieldNumber = 6;
        private static readonly pb::FieldCodec<global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Callee> _repeated_calleeList_codec
            = pb::FieldCodec.ForMessage(50, global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Callee.Parser);
        private readonly pbc::RepeatedField<global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Callee> calleeList_ = new pbc::RepeatedField<global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Callee>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Callee> CalleeList {
          get { return calleeList_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Debug);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Debug other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (FetchedFromDb != other.FetchedFromDb) return false;
          if (FetchedFromFanout != other.FetchedFromFanout) return false;
          if (FetchedFromPlayerMapper != other.FetchedFromPlayerMapper) return false;
          if (FetchedFromStatusCache != other.FetchedFromStatusCache) return false;
          if (FailedToFetch != other.FailedToFetch) return false;
          if(!calleeList_.Equals(other.calleeList_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (FetchedFromDb != 0) hash ^= FetchedFromDb.GetHashCode();
          if (FetchedFromFanout != 0) hash ^= FetchedFromFanout.GetHashCode();
          if (FetchedFromPlayerMapper != 0) hash ^= FetchedFromPlayerMapper.GetHashCode();
          if (FetchedFromStatusCache != 0) hash ^= FetchedFromStatusCache.GetHashCode();
          if (FailedToFetch != 0) hash ^= FailedToFetch.GetHashCode();
          hash ^= calleeList_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (FetchedFromDb != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(FetchedFromDb);
          }
          if (FetchedFromFanout != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(FetchedFromFanout);
          }
          if (FetchedFromPlayerMapper != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(FetchedFromPlayerMapper);
          }
          if (FetchedFromStatusCache != 0) {
            output.WriteRawTag(32);
            output.WriteInt32(FetchedFromStatusCache);
          }
          if (FailedToFetch != 0) {
            output.WriteRawTag(40);
            output.WriteInt32(FailedToFetch);
          }
          calleeList_.WriteTo(output, _repeated_calleeList_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (FetchedFromDb != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(FetchedFromDb);
          }
          if (FetchedFromFanout != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(FetchedFromFanout);
          }
          if (FetchedFromPlayerMapper != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(FetchedFromPlayerMapper);
          }
          if (FetchedFromStatusCache != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(FetchedFromStatusCache);
          }
          if (FailedToFetch != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(FailedToFetch);
          }
          size += calleeList_.CalculateSize(_repeated_calleeList_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Debug other) {
          if (other == null) {
            return;
          }
          if (other.FetchedFromDb != 0) {
            FetchedFromDb = other.FetchedFromDb;
          }
          if (other.FetchedFromFanout != 0) {
            FetchedFromFanout = other.FetchedFromFanout;
          }
          if (other.FetchedFromPlayerMapper != 0) {
            FetchedFromPlayerMapper = other.FetchedFromPlayerMapper;
          }
          if (other.FetchedFromStatusCache != 0) {
            FetchedFromStatusCache = other.FetchedFromStatusCache;
          }
          if (other.FailedToFetch != 0) {
            FailedToFetch = other.FailedToFetch;
          }
          calleeList_.Add(other.calleeList_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                FetchedFromDb = input.ReadInt32();
                break;
              }
              case 16: {
                FetchedFromFanout = input.ReadInt32();
                break;
              }
              case 24: {
                FetchedFromPlayerMapper = input.ReadInt32();
                break;
              }
              case 32: {
                FetchedFromStatusCache = input.ReadInt32();
                break;
              }
              case 40: {
                FailedToFetch = input.ReadInt32();
                break;
              }
              case 50: {
                calleeList_.AddEntriesFrom(input, _repeated_calleeList_codec);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Debug message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          public sealed partial class Callee : pb::IMessage<Callee> {
            private static readonly pb::MessageParser<Callee> _parser = new pb::MessageParser<Callee>(() => new Callee());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<Callee> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::POGOProtos.Networking.Responses.Social.GetFriendDetailsResponse.Types.Debug.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Callee() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Callee(Callee other) : this() {
              calleeId_ = other.calleeId_.Clone();
              playerId_ = other.playerId_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Callee Clone() {
              return new Callee(this);
            }

            /// <summary>Field number for the "callee_id" field.</summary>
            public const int CalleeIdFieldNumber = 1;
            private static readonly pb::FieldCodec<int> _repeated_calleeId_codec
                = pb::FieldCodec.ForInt32(10);
            private readonly pbc::RepeatedField<int> calleeId_ = new pbc::RepeatedField<int>();
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public pbc::RepeatedField<int> CalleeId {
              get { return calleeId_; }
            }

            /// <summary>Field number for the "player_id" field.</summary>
            public const int PlayerIdFieldNumber = 2;
            private string playerId_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string PlayerId {
              get { return playerId_; }
              set {
                playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as Callee);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(Callee other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if(!calleeId_.Equals(other.calleeId_)) return false;
              if (PlayerId != other.PlayerId) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              hash ^= calleeId_.GetHashCode();
              if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              calleeId_.WriteTo(output, _repeated_calleeId_codec);
              if (PlayerId.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(PlayerId);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              size += calleeId_.CalculateSize(_repeated_calleeId_codec);
              if (PlayerId.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(Callee other) {
              if (other == null) {
                return;
              }
              calleeId_.Add(other.calleeId_);
              if (other.PlayerId.Length != 0) {
                PlayerId = other.PlayerId;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10:
                  case 8: {
                    calleeId_.AddEntriesFrom(input, _repeated_calleeId_codec);
                    break;
                  }
                  case 18: {
                    PlayerId = input.ReadString();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
