// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Networking/Responses/Social/GetFriendshipRewardsResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses.Social {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/Social/GetFriendshipRewardsResponse.proto</summary>
  public static partial class GetFriendshipRewardsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/Social/GetFriendshipRewardsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetFriendshipRewardsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CklQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL1NvY2lhbC9HZXRG",
            "cmllbmRzaGlwUmV3YXJkc1Jlc3BvbnNlLnByb3RvEiZQT0dPUHJvdG9zLk5l",
            "dHdvcmtpbmcuUmVzcG9uc2VzLlNvY2lhbCKvAgocR2V0RnJpZW5kc2hpcFJl",
            "d2FyZHNSZXNwb25zZRJbCgZyZXN1bHQYASABKA4ySy5QT0dPUHJvdG9zLk5l",
            "dHdvcmtpbmcuUmVzcG9uc2VzLlNvY2lhbC5HZXRGcmllbmRzaGlwUmV3YXJk",
            "c1Jlc3BvbnNlLlJlc3VsdBIRCgl4cF9yZXdhcmQYAiABKAMSEQoJZnJpZW5k",
            "X2lkGAMgASgJIosBCgZSZXN1bHQSCQoFVU5TRVQQABILCgdTVUNDRVNTEAES",
            "EQoNRVJST1JfVU5LTk9XThACEhUKEUVSUk9SX05PVF9GUklFTkRTEAMSIwof",
            "RVJST1JfTUlMRVNUT05FX0FMUkVBRFlfQVdBUkRFRBAEEhoKFkVSUk9SX0ZB",
            "SUxFRF9UT19VUERBVEUQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.Social.GetFriendshipRewardsResponse), global::POGOProtos.Networking.Responses.Social.GetFriendshipRewardsResponse.Parser, new[]{ "Result", "XpReward", "FriendId" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.Social.GetFriendshipRewardsResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetFriendshipRewardsResponse : pb::IMessage<GetFriendshipRewardsResponse> {
    private static readonly pb::MessageParser<GetFriendshipRewardsResponse> _parser = new pb::MessageParser<GetFriendshipRewardsResponse>(() => new GetFriendshipRewardsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetFriendshipRewardsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.Social.GetFriendshipRewardsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFriendshipRewardsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFriendshipRewardsResponse(GetFriendshipRewardsResponse other) : this() {
      result_ = other.result_;
      xpReward_ = other.xpReward_;
      friendId_ = other.friendId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetFriendshipRewardsResponse Clone() {
      return new GetFriendshipRewardsResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.Social.GetFriendshipRewardsResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.Social.GetFriendshipRewardsResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "xp_reward" field.</summary>
    public const int XpRewardFieldNumber = 2;
    private long xpReward_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long XpReward {
      get { return xpReward_; }
      set {
        xpReward_ = value;
      }
    }

    /// <summary>Field number for the "friend_id" field.</summary>
    public const int FriendIdFieldNumber = 3;
    private string friendId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FriendId {
      get { return friendId_; }
      set {
        friendId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetFriendshipRewardsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetFriendshipRewardsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (XpReward != other.XpReward) return false;
      if (FriendId != other.FriendId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (XpReward != 0L) hash ^= XpReward.GetHashCode();
      if (FriendId.Length != 0) hash ^= FriendId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (XpReward != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(XpReward);
      }
      if (FriendId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FriendId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (XpReward != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(XpReward);
      }
      if (FriendId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FriendId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetFriendshipRewardsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.XpReward != 0L) {
        XpReward = other.XpReward;
      }
      if (other.FriendId.Length != 0) {
        FriendId = other.FriendId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.Social.GetFriendshipRewardsResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 16: {
            XpReward = input.ReadInt64();
            break;
          }
          case 26: {
            FriendId = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GetFriendshipRewardsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_UNKNOWN")] ErrorUnknown = 2,
        [pbr::OriginalName("ERROR_NOT_FRIENDS")] ErrorNotFriends = 3,
        [pbr::OriginalName("ERROR_MILESTONE_ALREADY_AWARDED")] ErrorMilestoneAlreadyAwarded = 4,
        [pbr::OriginalName("ERROR_FAILED_TO_UPDATE")] ErrorFailedToUpdate = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
