// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Networking/Responses/Social/GetGiftBoxDetailsResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses.Social {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/Social/GetGiftBoxDetailsResponse.proto</summary>
  public static partial class GetGiftBoxDetailsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/Social/GetGiftBoxDetailsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetGiftBoxDetailsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkZQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL1NvY2lhbC9HZXRH",
            "aWZ0Qm94RGV0YWlsc1Jlc3BvbnNlLnByb3RvEiZQT0dPUHJvdG9zLk5ldHdv",
            "cmtpbmcuUmVzcG9uc2VzLlNvY2lhbBopUE9HT1Byb3Rvcy9EYXRhL0dpZnQv",
            "R2lmdEJveERldGFpbHMucHJvdG8i1AIKGUdldEdpZnRCb3hEZXRhaWxzUmVz",
            "cG9uc2USWAoGcmVzdWx0GAEgASgOMkguUE9HT1Byb3Rvcy5OZXR3b3JraW5n",
            "LlJlc3BvbnNlcy5Tb2NpYWwuR2V0R2lmdEJveERldGFpbHNSZXNwb25zZS5S",
            "ZXN1bHQSOAoKZ2lmdF9ib3hlcxgCIAMoCzIkLlBPR09Qcm90b3MuRGF0YS5H",
            "aWZ0LkdpZnRCb3hEZXRhaWxzIqIBCgZSZXN1bHQSCQoFVU5TRVQQABILCgdT",
            "VUNDRVNTEAESEQoNRVJST1JfVU5LTk9XThACEh0KGUVSUk9SX0dJRlRfRE9F",
            "U19OT1RfRVhJU1QQAxIbChdFUlJPUl9JTlZBTElEX1BMQVlFUl9JRBAEEhoK",
            "FkVSUk9SX0ZSSUVORF9OT1RfRk9VTkQQBRIVChFFUlJPUl9GT1JUX1NFQVJD",
            "SBAGYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Gift.GiftBoxDetailsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.Social.GetGiftBoxDetailsResponse), global::POGOProtos.Networking.Responses.Social.GetGiftBoxDetailsResponse.Parser, new[]{ "Result", "GiftBoxes" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.Social.GetGiftBoxDetailsResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetGiftBoxDetailsResponse : pb::IMessage<GetGiftBoxDetailsResponse> {
    private static readonly pb::MessageParser<GetGiftBoxDetailsResponse> _parser = new pb::MessageParser<GetGiftBoxDetailsResponse>(() => new GetGiftBoxDetailsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetGiftBoxDetailsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.Social.GetGiftBoxDetailsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetGiftBoxDetailsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetGiftBoxDetailsResponse(GetGiftBoxDetailsResponse other) : this() {
      result_ = other.result_;
      giftBoxes_ = other.giftBoxes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetGiftBoxDetailsResponse Clone() {
      return new GetGiftBoxDetailsResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.Social.GetGiftBoxDetailsResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.Social.GetGiftBoxDetailsResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "gift_boxes" field.</summary>
    public const int GiftBoxesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Gift.GiftBoxDetails> _repeated_giftBoxes_codec
        = pb::FieldCodec.ForMessage(18, global::POGOProtos.Data.Gift.GiftBoxDetails.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Gift.GiftBoxDetails> giftBoxes_ = new pbc::RepeatedField<global::POGOProtos.Data.Gift.GiftBoxDetails>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Gift.GiftBoxDetails> GiftBoxes {
      get { return giftBoxes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetGiftBoxDetailsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetGiftBoxDetailsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!giftBoxes_.Equals(other.giftBoxes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      hash ^= giftBoxes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      giftBoxes_.WriteTo(output, _repeated_giftBoxes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      size += giftBoxes_.CalculateSize(_repeated_giftBoxes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetGiftBoxDetailsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      giftBoxes_.Add(other.giftBoxes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.Social.GetGiftBoxDetailsResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            giftBoxes_.AddEntriesFrom(input, _repeated_giftBoxes_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GetGiftBoxDetailsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_UNKNOWN")] ErrorUnknown = 2,
        [pbr::OriginalName("ERROR_GIFT_DOES_NOT_EXIST")] ErrorGiftDoesNotExist = 3,
        [pbr::OriginalName("ERROR_INVALID_PLAYER_ID")] ErrorInvalidPlayerId = 4,
        [pbr::OriginalName("ERROR_FRIEND_NOT_FOUND")] ErrorFriendNotFound = 5,
        [pbr::OriginalName("ERROR_FORT_SEARCH")] ErrorFortSearch = 6,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
