// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Networking/Responses/Social/SendGiftResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses.Social {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/Social/SendGiftResponse.proto</summary>
  public static partial class SendGiftResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/Social/SendGiftResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SendGiftResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj1QT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL1NvY2lhbC9TZW5k",
            "R2lmdFJlc3BvbnNlLnByb3RvEiZQT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVz",
            "cG9uc2VzLlNvY2lhbCLNAgoQU2VuZEdpZnRSZXNwb25zZRJPCgZyZXN1bHQY",
            "ASABKA4yPy5QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9uc2VzLlNvY2lh",
            "bC5TZW5kR2lmdFJlc3BvbnNlLlJlc3VsdBISCgphd2FyZGVkX3hwGAIgASgF",
            "ItMBCgZSZXN1bHQSCQoFVU5TRVQQABILCgdTVUNDRVNTEAESEQoNRVJST1Jf",
            "VU5LTk9XThACEh8KG0VSUk9SX1BMQVlFUl9ET0VTX05PVF9FWElTVBADEh0K",
            "GUVSUk9SX0dJRlRfRE9FU19OT1RfRVhJU1QQBBIhCh1FUlJPUl9HSUZUX0FM",
            "UkVBRFlfU0VOVF9UT0RBWRAFEiIKHkVSUk9SX1BMQVlFUl9IQVNfVU5PUEVO",
            "RURfR0lGVBAGEhcKE0VSUk9SX0ZSSUVORF9VUERBVEUQB2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.Social.SendGiftResponse), global::POGOProtos.Networking.Responses.Social.SendGiftResponse.Parser, new[]{ "Result", "AwardedXp" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.Social.SendGiftResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SendGiftResponse : pb::IMessage<SendGiftResponse> {
    private static readonly pb::MessageParser<SendGiftResponse> _parser = new pb::MessageParser<SendGiftResponse>(() => new SendGiftResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SendGiftResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.Social.SendGiftResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendGiftResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendGiftResponse(SendGiftResponse other) : this() {
      result_ = other.result_;
      awardedXp_ = other.awardedXp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SendGiftResponse Clone() {
      return new SendGiftResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.Social.SendGiftResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.Social.SendGiftResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "awarded_xp" field.</summary>
    public const int AwardedXpFieldNumber = 2;
    private int awardedXp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AwardedXp {
      get { return awardedXp_; }
      set {
        awardedXp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SendGiftResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SendGiftResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (AwardedXp != other.AwardedXp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (AwardedXp != 0) hash ^= AwardedXp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (AwardedXp != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AwardedXp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (AwardedXp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AwardedXp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SendGiftResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.AwardedXp != 0) {
        AwardedXp = other.AwardedXp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.Social.SendGiftResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 16: {
            AwardedXp = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the SendGiftResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_UNKNOWN")] ErrorUnknown = 2,
        [pbr::OriginalName("ERROR_PLAYER_DOES_NOT_EXIST")] ErrorPlayerDoesNotExist = 3,
        [pbr::OriginalName("ERROR_GIFT_DOES_NOT_EXIST")] ErrorGiftDoesNotExist = 4,
        [pbr::OriginalName("ERROR_GIFT_ALREADY_SENT_TODAY")] ErrorGiftAlreadySentToday = 5,
        [pbr::OriginalName("ERROR_PLAYER_HAS_UNOPENED_GIFT")] ErrorPlayerHasUnopenedGift = 6,
        [pbr::OriginalName("ERROR_FRIEND_UPDATE")] ErrorFriendUpdate = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
