// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/AssetCache/JournalRemoveEntry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.AssetCache {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/AssetCache/JournalRemoveEntry.proto</summary>
  public static partial class JournalRemoveEntryReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/AssetCache/JournalRemoveEntry.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static JournalRemoveEntryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNQT0dPUHJvdG9zL0RhdGEvQXNzZXRDYWNoZS9Kb3VybmFsUmVtb3ZlRW50",
            "cnkucHJvdG8SGlBPR09Qcm90b3MuRGF0YS5Bc3NldENhY2hlGipQT0dPUHJv",
            "dG9zL0RhdGEvQXNzZXRDYWNoZS9IYXNoZWRLZXkucHJvdG8iTwoSSm91cm5h",
            "bFJlbW92ZUVudHJ5EjkKCmhhc2hlZF9rZXkYASABKAsyJS5QT0dPUHJvdG9z",
            "LkRhdGEuQXNzZXRDYWNoZS5IYXNoZWRLZXliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.AssetCache.HashedKeyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.AssetCache.JournalRemoveEntry), global::POGOProtos.Data.AssetCache.JournalRemoveEntry.Parser, new[]{ "HashedKey" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class JournalRemoveEntry : pb::IMessage<JournalRemoveEntry> {
    private static readonly pb::MessageParser<JournalRemoveEntry> _parser = new pb::MessageParser<JournalRemoveEntry>(() => new JournalRemoveEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JournalRemoveEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.AssetCache.JournalRemoveEntryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JournalRemoveEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JournalRemoveEntry(JournalRemoveEntry other) : this() {
      hashedKey_ = other.hashedKey_ != null ? other.hashedKey_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JournalRemoveEntry Clone() {
      return new JournalRemoveEntry(this);
    }

    /// <summary>Field number for the "hashed_key" field.</summary>
    public const int HashedKeyFieldNumber = 1;
    private global::POGOProtos.Data.AssetCache.HashedKey hashedKey_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.AssetCache.HashedKey HashedKey {
      get { return hashedKey_; }
      set {
        hashedKey_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JournalRemoveEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JournalRemoveEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(HashedKey, other.HashedKey)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (hashedKey_ != null) hash ^= HashedKey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (hashedKey_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(HashedKey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (hashedKey_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HashedKey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JournalRemoveEntry other) {
      if (other == null) {
        return;
      }
      if (other.hashedKey_ != null) {
        if (hashedKey_ == null) {
          hashedKey_ = new global::POGOProtos.Data.AssetCache.HashedKey();
        }
        HashedKey.MergeFrom(other.HashedKey);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (hashedKey_ == null) {
              hashedKey_ = new global::POGOProtos.Data.AssetCache.HashedKey();
            }
            input.ReadMessage(hashedKey_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
