// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Friends/FriendshipLevelData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Friends {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Friends/FriendshipLevelData.proto</summary>
  public static partial class FriendshipLevelDataReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Friends/FriendshipLevelData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FriendshipLevelDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFQT0dPUHJvdG9zL0RhdGEvRnJpZW5kcy9GcmllbmRzaGlwTGV2ZWxEYXRh",
            "LnByb3RvEhdQT0dPUHJvdG9zLkRhdGEuRnJpZW5kcxovUE9HT1Byb3Rvcy9F",
            "bnVtcy9GcmllbmRzaGlwTGV2ZWxNaWxlc3RvbmUucHJvdG8iwwIKE0ZyaWVu",
            "ZHNoaXBMZXZlbERhdGESDgoGYnVja2V0GAEgASgDEhsKE3BvaW50c19lYXJu",
            "ZWRfdG9kYXkYAiABKAUSUAocYXdhcmRlZF9mcmllbmRzaGlwX21pbGVzdG9u",
            "ZRgDIAEoDjIqLlBPR09Qcm90b3MuRW51bXMuRnJpZW5kc2hpcExldmVsTWls",
            "ZXN0b25lElAKHGN1cnJlbnRfZnJpZW5kc2hpcF9taWxlc3RvbmUYBCABKA4y",
            "Ki5QT0dPUHJvdG9zLkVudW1zLkZyaWVuZHNoaXBMZXZlbE1pbGVzdG9uZRI1",
            "Ci1uZXh0X2ZyaWVuZHNoaXBfbWlsZXN0b25lX3Byb2dyZXNzX3BlcmNlbnRh",
            "Z2UYBSABKAESJAoccG9pbnRzX3Rvd2FyZF9uZXh0X21pbGVzdG9uZRgGIAEo",
            "BWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Enums.FriendshipLevelMilestoneReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Friends.FriendshipLevelData), global::POGOProtos.Data.Friends.FriendshipLevelData.Parser, new[]{ "Bucket", "PointsEarnedToday", "AwardedFriendshipMilestone", "CurrentFriendshipMilestone", "NextFriendshipMilestoneProgressPercentage", "PointsTowardNextMilestone" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FriendshipLevelData : pb::IMessage<FriendshipLevelData> {
    private static readonly pb::MessageParser<FriendshipLevelData> _parser = new pb::MessageParser<FriendshipLevelData>(() => new FriendshipLevelData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FriendshipLevelData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Friends.FriendshipLevelDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendshipLevelData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendshipLevelData(FriendshipLevelData other) : this() {
      bucket_ = other.bucket_;
      pointsEarnedToday_ = other.pointsEarnedToday_;
      awardedFriendshipMilestone_ = other.awardedFriendshipMilestone_;
      currentFriendshipMilestone_ = other.currentFriendshipMilestone_;
      nextFriendshipMilestoneProgressPercentage_ = other.nextFriendshipMilestoneProgressPercentage_;
      pointsTowardNextMilestone_ = other.pointsTowardNextMilestone_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendshipLevelData Clone() {
      return new FriendshipLevelData(this);
    }

    /// <summary>Field number for the "bucket" field.</summary>
    public const int BucketFieldNumber = 1;
    private long bucket_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Bucket {
      get { return bucket_; }
      set {
        bucket_ = value;
      }
    }

    /// <summary>Field number for the "points_earned_today" field.</summary>
    public const int PointsEarnedTodayFieldNumber = 2;
    private int pointsEarnedToday_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PointsEarnedToday {
      get { return pointsEarnedToday_; }
      set {
        pointsEarnedToday_ = value;
      }
    }

    /// <summary>Field number for the "awarded_friendship_milestone" field.</summary>
    public const int AwardedFriendshipMilestoneFieldNumber = 3;
    private global::POGOProtos.Enums.FriendshipLevelMilestone awardedFriendshipMilestone_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Enums.FriendshipLevelMilestone AwardedFriendshipMilestone {
      get { return awardedFriendshipMilestone_; }
      set {
        awardedFriendshipMilestone_ = value;
      }
    }

    /// <summary>Field number for the "current_friendship_milestone" field.</summary>
    public const int CurrentFriendshipMilestoneFieldNumber = 4;
    private global::POGOProtos.Enums.FriendshipLevelMilestone currentFriendshipMilestone_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Enums.FriendshipLevelMilestone CurrentFriendshipMilestone {
      get { return currentFriendshipMilestone_; }
      set {
        currentFriendshipMilestone_ = value;
      }
    }

    /// <summary>Field number for the "next_friendship_milestone_progress_percentage" field.</summary>
    public const int NextFriendshipMilestoneProgressPercentageFieldNumber = 5;
    private double nextFriendshipMilestoneProgressPercentage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double NextFriendshipMilestoneProgressPercentage {
      get { return nextFriendshipMilestoneProgressPercentage_; }
      set {
        nextFriendshipMilestoneProgressPercentage_ = value;
      }
    }

    /// <summary>Field number for the "points_toward_next_milestone" field.</summary>
    public const int PointsTowardNextMilestoneFieldNumber = 6;
    private int pointsTowardNextMilestone_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PointsTowardNextMilestone {
      get { return pointsTowardNextMilestone_; }
      set {
        pointsTowardNextMilestone_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FriendshipLevelData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FriendshipLevelData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Bucket != other.Bucket) return false;
      if (PointsEarnedToday != other.PointsEarnedToday) return false;
      if (AwardedFriendshipMilestone != other.AwardedFriendshipMilestone) return false;
      if (CurrentFriendshipMilestone != other.CurrentFriendshipMilestone) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(NextFriendshipMilestoneProgressPercentage, other.NextFriendshipMilestoneProgressPercentage)) return false;
      if (PointsTowardNextMilestone != other.PointsTowardNextMilestone) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Bucket != 0L) hash ^= Bucket.GetHashCode();
      if (PointsEarnedToday != 0) hash ^= PointsEarnedToday.GetHashCode();
      if (AwardedFriendshipMilestone != 0) hash ^= AwardedFriendshipMilestone.GetHashCode();
      if (CurrentFriendshipMilestone != 0) hash ^= CurrentFriendshipMilestone.GetHashCode();
      if (NextFriendshipMilestoneProgressPercentage != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(NextFriendshipMilestoneProgressPercentage);
      if (PointsTowardNextMilestone != 0) hash ^= PointsTowardNextMilestone.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Bucket != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Bucket);
      }
      if (PointsEarnedToday != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PointsEarnedToday);
      }
      if (AwardedFriendshipMilestone != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) AwardedFriendshipMilestone);
      }
      if (CurrentFriendshipMilestone != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) CurrentFriendshipMilestone);
      }
      if (NextFriendshipMilestoneProgressPercentage != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(NextFriendshipMilestoneProgressPercentage);
      }
      if (PointsTowardNextMilestone != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(PointsTowardNextMilestone);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Bucket != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Bucket);
      }
      if (PointsEarnedToday != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PointsEarnedToday);
      }
      if (AwardedFriendshipMilestone != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AwardedFriendshipMilestone);
      }
      if (CurrentFriendshipMilestone != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CurrentFriendshipMilestone);
      }
      if (NextFriendshipMilestoneProgressPercentage != 0D) {
        size += 1 + 8;
      }
      if (PointsTowardNextMilestone != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PointsTowardNextMilestone);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FriendshipLevelData other) {
      if (other == null) {
        return;
      }
      if (other.Bucket != 0L) {
        Bucket = other.Bucket;
      }
      if (other.PointsEarnedToday != 0) {
        PointsEarnedToday = other.PointsEarnedToday;
      }
      if (other.AwardedFriendshipMilestone != 0) {
        AwardedFriendshipMilestone = other.AwardedFriendshipMilestone;
      }
      if (other.CurrentFriendshipMilestone != 0) {
        CurrentFriendshipMilestone = other.CurrentFriendshipMilestone;
      }
      if (other.NextFriendshipMilestoneProgressPercentage != 0D) {
        NextFriendshipMilestoneProgressPercentage = other.NextFriendshipMilestoneProgressPercentage;
      }
      if (other.PointsTowardNextMilestone != 0) {
        PointsTowardNextMilestone = other.PointsTowardNextMilestone;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Bucket = input.ReadInt64();
            break;
          }
          case 16: {
            PointsEarnedToday = input.ReadInt32();
            break;
          }
          case 24: {
            awardedFriendshipMilestone_ = (global::POGOProtos.Enums.FriendshipLevelMilestone) input.ReadEnum();
            break;
          }
          case 32: {
            currentFriendshipMilestone_ = (global::POGOProtos.Enums.FriendshipLevelMilestone) input.ReadEnum();
            break;
          }
          case 41: {
            NextFriendshipMilestoneProgressPercentage = input.ReadDouble();
            break;
          }
          case 48: {
            PointsTowardNextMilestone = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
