// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Friends/LeveledUpFriends.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Friends {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Friends/LeveledUpFriends.proto</summary>
  public static partial class LeveledUpFriendsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Friends/LeveledUpFriends.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LeveledUpFriendsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5QT0dPUHJvdG9zL0RhdGEvRnJpZW5kcy9MZXZlbGVkVXBGcmllbmRzLnBy",
            "b3RvEhdQT0dPUHJvdG9zLkRhdGEuRnJpZW5kcxowUE9HT1Byb3Rvcy9EYXRh",
            "L1BsYXllci9QbGF5ZXJQdWJsaWNQcm9maWxlLnByb3RvGjFQT0dPUHJvdG9z",
            "L0RhdGEvRnJpZW5kcy9GcmllbmRzaGlwTGV2ZWxEYXRhLnByb3RvIqcBChBM",
            "ZXZlbGVkVXBGcmllbmRzEkQKD2ZyaWVuZF9wcm9maWxlcxgBIAMoCzIrLlBP",
            "R09Qcm90b3MuRGF0YS5QbGF5ZXIuUGxheWVyUHVibGljUHJvZmlsZRJNChdm",
            "cmllbmRfbWlsZXN0b25lX2xldmVscxgCIAMoCzIsLlBPR09Qcm90b3MuRGF0",
            "YS5GcmllbmRzLkZyaWVuZHNoaXBMZXZlbERhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Player.PlayerPublicProfileReflection.Descriptor, global::POGOProtos.Data.Friends.FriendshipLevelDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Friends.LeveledUpFriends), global::POGOProtos.Data.Friends.LeveledUpFriends.Parser, new[]{ "FriendProfiles", "FriendMilestoneLevels" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LeveledUpFriends : pb::IMessage<LeveledUpFriends> {
    private static readonly pb::MessageParser<LeveledUpFriends> _parser = new pb::MessageParser<LeveledUpFriends>(() => new LeveledUpFriends());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeveledUpFriends> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Friends.LeveledUpFriendsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeveledUpFriends() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeveledUpFriends(LeveledUpFriends other) : this() {
      friendProfiles_ = other.friendProfiles_.Clone();
      friendMilestoneLevels_ = other.friendMilestoneLevels_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeveledUpFriends Clone() {
      return new LeveledUpFriends(this);
    }

    /// <summary>Field number for the "friend_profiles" field.</summary>
    public const int FriendProfilesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Player.PlayerPublicProfile> _repeated_friendProfiles_codec
        = pb::FieldCodec.ForMessage(10, global::POGOProtos.Data.Player.PlayerPublicProfile.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Player.PlayerPublicProfile> friendProfiles_ = new pbc::RepeatedField<global::POGOProtos.Data.Player.PlayerPublicProfile>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Player.PlayerPublicProfile> FriendProfiles {
      get { return friendProfiles_; }
    }

    /// <summary>Field number for the "friend_milestone_levels" field.</summary>
    public const int FriendMilestoneLevelsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Friends.FriendshipLevelData> _repeated_friendMilestoneLevels_codec
        = pb::FieldCodec.ForMessage(18, global::POGOProtos.Data.Friends.FriendshipLevelData.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Friends.FriendshipLevelData> friendMilestoneLevels_ = new pbc::RepeatedField<global::POGOProtos.Data.Friends.FriendshipLevelData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Friends.FriendshipLevelData> FriendMilestoneLevels {
      get { return friendMilestoneLevels_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeveledUpFriends);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeveledUpFriends other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!friendProfiles_.Equals(other.friendProfiles_)) return false;
      if(!friendMilestoneLevels_.Equals(other.friendMilestoneLevels_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= friendProfiles_.GetHashCode();
      hash ^= friendMilestoneLevels_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      friendProfiles_.WriteTo(output, _repeated_friendProfiles_codec);
      friendMilestoneLevels_.WriteTo(output, _repeated_friendMilestoneLevels_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += friendProfiles_.CalculateSize(_repeated_friendProfiles_codec);
      size += friendMilestoneLevels_.CalculateSize(_repeated_friendMilestoneLevels_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeveledUpFriends other) {
      if (other == null) {
        return;
      }
      friendProfiles_.Add(other.friendProfiles_);
      friendMilestoneLevels_.Add(other.friendMilestoneLevels_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            friendProfiles_.AddEntriesFrom(input, _repeated_friendProfiles_codec);
            break;
          }
          case 18: {
            friendMilestoneLevels_.AddEntriesFrom(input, _repeated_friendMilestoneLevels_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
