// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Friends/OutgoingFriendInviteDisplay.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Friends {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Friends/OutgoingFriendInviteDisplay.proto</summary>
  public static partial class OutgoingFriendInviteDisplayReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Friends/OutgoingFriendInviteDisplay.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OutgoingFriendInviteDisplayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjlQT0dPUHJvdG9zL0RhdGEvRnJpZW5kcy9PdXRnb2luZ0ZyaWVuZEludml0",
            "ZURpc3BsYXkucHJvdG8SF1BPR09Qcm90b3MuRGF0YS5GcmllbmRzGjJQT0dP",
            "UHJvdG9zL0RhdGEvRnJpZW5kcy9PdXRnb2luZ0ZyaWVuZEludml0ZS5wcm90",
            "bxoqUE9HT1Byb3Rvcy9EYXRhL1BsYXllci9QbGF5ZXJTdW1tYXJ5LnByb3Rv",
            "IpMBChtPdXRnb2luZ0ZyaWVuZEludml0ZURpc3BsYXkSPQoGaW52aXRlGAEg",
            "ASgLMi0uUE9HT1Byb3Rvcy5EYXRhLkZyaWVuZHMuT3V0Z29pbmdGcmllbmRJ",
            "bnZpdGUSNQoGcGxheWVyGAIgASgLMiUuUE9HT1Byb3Rvcy5EYXRhLlBsYXll",
            "ci5QbGF5ZXJTdW1tYXJ5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Friends.OutgoingFriendInviteReflection.Descriptor, global::POGOProtos.Data.Player.PlayerSummaryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Friends.OutgoingFriendInviteDisplay), global::POGOProtos.Data.Friends.OutgoingFriendInviteDisplay.Parser, new[]{ "Invite", "Player" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OutgoingFriendInviteDisplay : pb::IMessage<OutgoingFriendInviteDisplay> {
    private static readonly pb::MessageParser<OutgoingFriendInviteDisplay> _parser = new pb::MessageParser<OutgoingFriendInviteDisplay>(() => new OutgoingFriendInviteDisplay());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutgoingFriendInviteDisplay> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Friends.OutgoingFriendInviteDisplayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutgoingFriendInviteDisplay() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutgoingFriendInviteDisplay(OutgoingFriendInviteDisplay other) : this() {
      invite_ = other.invite_ != null ? other.invite_.Clone() : null;
      player_ = other.player_ != null ? other.player_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutgoingFriendInviteDisplay Clone() {
      return new OutgoingFriendInviteDisplay(this);
    }

    /// <summary>Field number for the "invite" field.</summary>
    public const int InviteFieldNumber = 1;
    private global::POGOProtos.Data.Friends.OutgoingFriendInvite invite_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Friends.OutgoingFriendInvite Invite {
      get { return invite_; }
      set {
        invite_ = value;
      }
    }

    /// <summary>Field number for the "player" field.</summary>
    public const int PlayerFieldNumber = 2;
    private global::POGOProtos.Data.Player.PlayerSummary player_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Player.PlayerSummary Player {
      get { return player_; }
      set {
        player_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutgoingFriendInviteDisplay);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutgoingFriendInviteDisplay other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Invite, other.Invite)) return false;
      if (!object.Equals(Player, other.Player)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (invite_ != null) hash ^= Invite.GetHashCode();
      if (player_ != null) hash ^= Player.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (invite_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Invite);
      }
      if (player_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Player);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (invite_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Invite);
      }
      if (player_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Player);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutgoingFriendInviteDisplay other) {
      if (other == null) {
        return;
      }
      if (other.invite_ != null) {
        if (invite_ == null) {
          invite_ = new global::POGOProtos.Data.Friends.OutgoingFriendInvite();
        }
        Invite.MergeFrom(other.Invite);
      }
      if (other.player_ != null) {
        if (player_ == null) {
          player_ = new global::POGOProtos.Data.Player.PlayerSummary();
        }
        Player.MergeFrom(other.Player);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (invite_ == null) {
              invite_ = new global::POGOProtos.Data.Friends.OutgoingFriendInvite();
            }
            input.ReadMessage(invite_);
            break;
          }
          case 18: {
            if (player_ == null) {
              player_ = new global::POGOProtos.Data.Player.PlayerSummary();
            }
            input.ReadMessage(player_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
