// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Friends/OutgoingFriendInvite.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Friends {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Friends/OutgoingFriendInvite.proto</summary>
  public static partial class OutgoingFriendInviteReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Friends/OutgoingFriendInvite.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OutgoingFriendInviteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJQT0dPUHJvdG9zL0RhdGEvRnJpZW5kcy9PdXRnb2luZ0ZyaWVuZEludml0",
            "ZS5wcm90bxIXUE9HT1Byb3Rvcy5EYXRhLkZyaWVuZHMiwgEKFE91dGdvaW5n",
            "RnJpZW5kSW52aXRlEkQKBnN0YXR1cxgBIAEoDjI0LlBPR09Qcm90b3MuRGF0",
            "YS5GcmllbmRzLk91dGdvaW5nRnJpZW5kSW52aXRlLlN0YXR1cxIRCglwbGF5",
            "ZXJfaWQYAiABKAkSEgoKY3JlYXRlZF9tcxgDIAEoAyI9CgZTdGF0dXMSCQoF",
            "VU5TRVQQABILCgdQRU5ESU5HEAESDQoJQ0FOQ0VMTEVEEAISDAoIREVDTElO",
            "RUQQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Friends.OutgoingFriendInvite), global::POGOProtos.Data.Friends.OutgoingFriendInvite.Parser, new[]{ "Status", "PlayerId", "CreatedMs" }, null, new[]{ typeof(global::POGOProtos.Data.Friends.OutgoingFriendInvite.Types.Status) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OutgoingFriendInvite : pb::IMessage<OutgoingFriendInvite> {
    private static readonly pb::MessageParser<OutgoingFriendInvite> _parser = new pb::MessageParser<OutgoingFriendInvite>(() => new OutgoingFriendInvite());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutgoingFriendInvite> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Friends.OutgoingFriendInviteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutgoingFriendInvite() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutgoingFriendInvite(OutgoingFriendInvite other) : this() {
      status_ = other.status_;
      playerId_ = other.playerId_;
      createdMs_ = other.createdMs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutgoingFriendInvite Clone() {
      return new OutgoingFriendInvite(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::POGOProtos.Data.Friends.OutgoingFriendInvite.Types.Status status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Friends.OutgoingFriendInvite.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private string playerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PlayerId {
      get { return playerId_; }
      set {
        playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "created_ms" field.</summary>
    public const int CreatedMsFieldNumber = 3;
    private long createdMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long CreatedMs {
      get { return createdMs_; }
      set {
        createdMs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutgoingFriendInvite);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutgoingFriendInvite other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (PlayerId != other.PlayerId) return false;
      if (CreatedMs != other.CreatedMs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
      if (CreatedMs != 0L) hash ^= CreatedMs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (PlayerId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PlayerId);
      }
      if (CreatedMs != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CreatedMs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (PlayerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
      }
      if (CreatedMs != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreatedMs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutgoingFriendInvite other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.PlayerId.Length != 0) {
        PlayerId = other.PlayerId;
      }
      if (other.CreatedMs != 0L) {
        CreatedMs = other.CreatedMs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            status_ = (global::POGOProtos.Data.Friends.OutgoingFriendInvite.Types.Status) input.ReadEnum();
            break;
          }
          case 18: {
            PlayerId = input.ReadString();
            break;
          }
          case 24: {
            CreatedMs = input.ReadInt64();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the OutgoingFriendInvite message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("PENDING")] Pending = 1,
        [pbr::OriginalName("CANCELLED")] Cancelled = 2,
        [pbr::OriginalName("DECLINED")] Declined = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
