// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Friends/PlayerFriendDisplay.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Friends {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Friends/PlayerFriendDisplay.proto</summary>
  public static partial class PlayerFriendDisplayReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Friends/PlayerFriendDisplay.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerFriendDisplayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFQT0dPUHJvdG9zL0RhdGEvRnJpZW5kcy9QbGF5ZXJGcmllbmREaXNwbGF5",
            "LnByb3RvEhdQT0dPUHJvdG9zLkRhdGEuRnJpZW5kcxokUE9HT1Byb3Rvcy9E",
            "YXRhL1Bva2Vtb25EaXNwbGF5LnByb3RvIrECChNQbGF5ZXJGcmllbmREaXNw",
            "bGF5Ei4KBWJ1ZGR5GAEgASgLMh8uUE9HT1Byb3Rvcy5EYXRhLlBva2Vtb25E",
            "aXNwbGF5EiAKGGJ1ZGR5X2Rpc3BsYXlfcG9rZW1vbl9pZBgCIAEoBRIeChZi",
            "dWRkeV9wb2tlbW9uX25pY2tuYW1lGAMgASgJEjwKE2xhc3RfcG9rZW1vbl9j",
            "YXVnaHQYBCABKAsyHy5QT0dPUHJvdG9zLkRhdGEuUG9rZW1vbkRpc3BsYXkS",
            "JgoebGFzdF9wb2tlbW9uX2NhdWdodF9kaXNwbGF5X2lkGAUgASgFEiUKHWxh",
            "c3RfcG9rZW1vbl9jYXVnaHRfdGltZXN0YW1wGAYgASgDEhsKE2J1ZGR5X2Nh",
            "bmR5X2F3YXJkZWQYByABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.PokemonDisplayReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Friends.PlayerFriendDisplay), global::POGOProtos.Data.Friends.PlayerFriendDisplay.Parser, new[]{ "Buddy", "BuddyDisplayPokemonId", "BuddyPokemonNickname", "LastPokemonCaught", "LastPokemonCaughtDisplayId", "LastPokemonCaughtTimestamp", "BuddyCandyAwarded" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlayerFriendDisplay : pb::IMessage<PlayerFriendDisplay> {
    private static readonly pb::MessageParser<PlayerFriendDisplay> _parser = new pb::MessageParser<PlayerFriendDisplay>(() => new PlayerFriendDisplay());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerFriendDisplay> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Friends.PlayerFriendDisplayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerFriendDisplay() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerFriendDisplay(PlayerFriendDisplay other) : this() {
      buddy_ = other.buddy_ != null ? other.buddy_.Clone() : null;
      buddyDisplayPokemonId_ = other.buddyDisplayPokemonId_;
      buddyPokemonNickname_ = other.buddyPokemonNickname_;
      lastPokemonCaught_ = other.lastPokemonCaught_ != null ? other.lastPokemonCaught_.Clone() : null;
      lastPokemonCaughtDisplayId_ = other.lastPokemonCaughtDisplayId_;
      lastPokemonCaughtTimestamp_ = other.lastPokemonCaughtTimestamp_;
      buddyCandyAwarded_ = other.buddyCandyAwarded_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerFriendDisplay Clone() {
      return new PlayerFriendDisplay(this);
    }

    /// <summary>Field number for the "buddy" field.</summary>
    public const int BuddyFieldNumber = 1;
    private global::POGOProtos.Data.PokemonDisplay buddy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.PokemonDisplay Buddy {
      get { return buddy_; }
      set {
        buddy_ = value;
      }
    }

    /// <summary>Field number for the "buddy_display_pokemon_id" field.</summary>
    public const int BuddyDisplayPokemonIdFieldNumber = 2;
    private int buddyDisplayPokemonId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuddyDisplayPokemonId {
      get { return buddyDisplayPokemonId_; }
      set {
        buddyDisplayPokemonId_ = value;
      }
    }

    /// <summary>Field number for the "buddy_pokemon_nickname" field.</summary>
    public const int BuddyPokemonNicknameFieldNumber = 3;
    private string buddyPokemonNickname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BuddyPokemonNickname {
      get { return buddyPokemonNickname_; }
      set {
        buddyPokemonNickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_pokemon_caught" field.</summary>
    public const int LastPokemonCaughtFieldNumber = 4;
    private global::POGOProtos.Data.PokemonDisplay lastPokemonCaught_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.PokemonDisplay LastPokemonCaught {
      get { return lastPokemonCaught_; }
      set {
        lastPokemonCaught_ = value;
      }
    }

    /// <summary>Field number for the "last_pokemon_caught_display_id" field.</summary>
    public const int LastPokemonCaughtDisplayIdFieldNumber = 5;
    private int lastPokemonCaughtDisplayId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LastPokemonCaughtDisplayId {
      get { return lastPokemonCaughtDisplayId_; }
      set {
        lastPokemonCaughtDisplayId_ = value;
      }
    }

    /// <summary>Field number for the "last_pokemon_caught_timestamp" field.</summary>
    public const int LastPokemonCaughtTimestampFieldNumber = 6;
    private long lastPokemonCaughtTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LastPokemonCaughtTimestamp {
      get { return lastPokemonCaughtTimestamp_; }
      set {
        lastPokemonCaughtTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "buddy_candy_awarded" field.</summary>
    public const int BuddyCandyAwardedFieldNumber = 7;
    private int buddyCandyAwarded_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuddyCandyAwarded {
      get { return buddyCandyAwarded_; }
      set {
        buddyCandyAwarded_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerFriendDisplay);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerFriendDisplay other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Buddy, other.Buddy)) return false;
      if (BuddyDisplayPokemonId != other.BuddyDisplayPokemonId) return false;
      if (BuddyPokemonNickname != other.BuddyPokemonNickname) return false;
      if (!object.Equals(LastPokemonCaught, other.LastPokemonCaught)) return false;
      if (LastPokemonCaughtDisplayId != other.LastPokemonCaughtDisplayId) return false;
      if (LastPokemonCaughtTimestamp != other.LastPokemonCaughtTimestamp) return false;
      if (BuddyCandyAwarded != other.BuddyCandyAwarded) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (buddy_ != null) hash ^= Buddy.GetHashCode();
      if (BuddyDisplayPokemonId != 0) hash ^= BuddyDisplayPokemonId.GetHashCode();
      if (BuddyPokemonNickname.Length != 0) hash ^= BuddyPokemonNickname.GetHashCode();
      if (lastPokemonCaught_ != null) hash ^= LastPokemonCaught.GetHashCode();
      if (LastPokemonCaughtDisplayId != 0) hash ^= LastPokemonCaughtDisplayId.GetHashCode();
      if (LastPokemonCaughtTimestamp != 0L) hash ^= LastPokemonCaughtTimestamp.GetHashCode();
      if (BuddyCandyAwarded != 0) hash ^= BuddyCandyAwarded.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (buddy_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Buddy);
      }
      if (BuddyDisplayPokemonId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(BuddyDisplayPokemonId);
      }
      if (BuddyPokemonNickname.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BuddyPokemonNickname);
      }
      if (lastPokemonCaught_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LastPokemonCaught);
      }
      if (LastPokemonCaughtDisplayId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(LastPokemonCaughtDisplayId);
      }
      if (LastPokemonCaughtTimestamp != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(LastPokemonCaughtTimestamp);
      }
      if (BuddyCandyAwarded != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(BuddyCandyAwarded);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (buddy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Buddy);
      }
      if (BuddyDisplayPokemonId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuddyDisplayPokemonId);
      }
      if (BuddyPokemonNickname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuddyPokemonNickname);
      }
      if (lastPokemonCaught_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastPokemonCaught);
      }
      if (LastPokemonCaughtDisplayId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastPokemonCaughtDisplayId);
      }
      if (LastPokemonCaughtTimestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LastPokemonCaughtTimestamp);
      }
      if (BuddyCandyAwarded != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuddyCandyAwarded);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerFriendDisplay other) {
      if (other == null) {
        return;
      }
      if (other.buddy_ != null) {
        if (buddy_ == null) {
          buddy_ = new global::POGOProtos.Data.PokemonDisplay();
        }
        Buddy.MergeFrom(other.Buddy);
      }
      if (other.BuddyDisplayPokemonId != 0) {
        BuddyDisplayPokemonId = other.BuddyDisplayPokemonId;
      }
      if (other.BuddyPokemonNickname.Length != 0) {
        BuddyPokemonNickname = other.BuddyPokemonNickname;
      }
      if (other.lastPokemonCaught_ != null) {
        if (lastPokemonCaught_ == null) {
          lastPokemonCaught_ = new global::POGOProtos.Data.PokemonDisplay();
        }
        LastPokemonCaught.MergeFrom(other.LastPokemonCaught);
      }
      if (other.LastPokemonCaughtDisplayId != 0) {
        LastPokemonCaughtDisplayId = other.LastPokemonCaughtDisplayId;
      }
      if (other.LastPokemonCaughtTimestamp != 0L) {
        LastPokemonCaughtTimestamp = other.LastPokemonCaughtTimestamp;
      }
      if (other.BuddyCandyAwarded != 0) {
        BuddyCandyAwarded = other.BuddyCandyAwarded;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (buddy_ == null) {
              buddy_ = new global::POGOProtos.Data.PokemonDisplay();
            }
            input.ReadMessage(buddy_);
            break;
          }
          case 16: {
            BuddyDisplayPokemonId = input.ReadInt32();
            break;
          }
          case 26: {
            BuddyPokemonNickname = input.ReadString();
            break;
          }
          case 34: {
            if (lastPokemonCaught_ == null) {
              lastPokemonCaught_ = new global::POGOProtos.Data.PokemonDisplay();
            }
            input.ReadMessage(lastPokemonCaught_);
            break;
          }
          case 40: {
            LastPokemonCaughtDisplayId = input.ReadInt32();
            break;
          }
          case 48: {
            LastPokemonCaughtTimestamp = input.ReadInt64();
            break;
          }
          case 56: {
            BuddyCandyAwarded = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
