// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/IapItemCategoryDisplay.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings.Master {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/Master/IapItemCategoryDisplay.proto</summary>
  public static partial class IapItemCategoryDisplayReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/Master/IapItemCategoryDisplay.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IapItemCategoryDisplayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjdQT0dPUHJvdG9zL1NldHRpbmdzL01hc3Rlci9JYXBJdGVtQ2F0ZWdvcnlE",
            "aXNwbGF5LnByb3RvEhpQT0dPUHJvdG9zLlNldHRpbmdzLk1hc3RlchomUE9H",
            "T1Byb3Rvcy9FbnVtcy9JYXBJdGVtQ2F0ZWdvcnkucHJvdG8i2QEKFklhcEl0",
            "ZW1DYXRlZ29yeURpc3BsYXkSNwoIY2F0ZWdvcnkYASABKA4yJS5QT0dPUHJv",
            "dG9zLkVudW1zLkhvbG9JYXBJdGVtQ2F0ZWdvcnkSDAoEbmFtZRgCIAEoCRIO",
            "CgZoaWRkZW4YAyABKAgSEgoKc29ydF9vcmRlchgEIAEoBRIWCg5iYW5uZXJf",
            "ZW5hYmxlZBgFIAEoCBIUCgxiYW5uZXJfdGl0bGUYBiABKAkSEQoJaW1hZ2Vf",
            "dXJsGAcgASgJEhMKC2Rlc2NyaXB0aW9uGAggASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Enums.IapItemCategoryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.Master.IapItemCategoryDisplay), global::POGOProtos.Settings.Master.IapItemCategoryDisplay.Parser, new[]{ "Category", "Name", "Hidden", "SortOrder", "BannerEnabled", "BannerTitle", "ImageUrl", "Description" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class IapItemCategoryDisplay : pb::IMessage<IapItemCategoryDisplay> {
    private static readonly pb::MessageParser<IapItemCategoryDisplay> _parser = new pb::MessageParser<IapItemCategoryDisplay>(() => new IapItemCategoryDisplay());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IapItemCategoryDisplay> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.Master.IapItemCategoryDisplayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IapItemCategoryDisplay() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IapItemCategoryDisplay(IapItemCategoryDisplay other) : this() {
      category_ = other.category_;
      name_ = other.name_;
      hidden_ = other.hidden_;
      sortOrder_ = other.sortOrder_;
      bannerEnabled_ = other.bannerEnabled_;
      bannerTitle_ = other.bannerTitle_;
      imageUrl_ = other.imageUrl_;
      description_ = other.description_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IapItemCategoryDisplay Clone() {
      return new IapItemCategoryDisplay(this);
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 1;
    private global::POGOProtos.Enums.HoloIapItemCategory category_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Enums.HoloIapItemCategory Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hidden" field.</summary>
    public const int HiddenFieldNumber = 3;
    private bool hidden_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Hidden {
      get { return hidden_; }
      set {
        hidden_ = value;
      }
    }

    /// <summary>Field number for the "sort_order" field.</summary>
    public const int SortOrderFieldNumber = 4;
    private int sortOrder_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SortOrder {
      get { return sortOrder_; }
      set {
        sortOrder_ = value;
      }
    }

    /// <summary>Field number for the "banner_enabled" field.</summary>
    public const int BannerEnabledFieldNumber = 5;
    private bool bannerEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BannerEnabled {
      get { return bannerEnabled_; }
      set {
        bannerEnabled_ = value;
      }
    }

    /// <summary>Field number for the "banner_title" field.</summary>
    public const int BannerTitleFieldNumber = 6;
    private string bannerTitle_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BannerTitle {
      get { return bannerTitle_; }
      set {
        bannerTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "image_url" field.</summary>
    public const int ImageUrlFieldNumber = 7;
    private string imageUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImageUrl {
      get { return imageUrl_; }
      set {
        imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 8;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IapItemCategoryDisplay);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IapItemCategoryDisplay other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Category != other.Category) return false;
      if (Name != other.Name) return false;
      if (Hidden != other.Hidden) return false;
      if (SortOrder != other.SortOrder) return false;
      if (BannerEnabled != other.BannerEnabled) return false;
      if (BannerTitle != other.BannerTitle) return false;
      if (ImageUrl != other.ImageUrl) return false;
      if (Description != other.Description) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Category != 0) hash ^= Category.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Hidden != false) hash ^= Hidden.GetHashCode();
      if (SortOrder != 0) hash ^= SortOrder.GetHashCode();
      if (BannerEnabled != false) hash ^= BannerEnabled.GetHashCode();
      if (BannerTitle.Length != 0) hash ^= BannerTitle.GetHashCode();
      if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Category != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Category);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Hidden != false) {
        output.WriteRawTag(24);
        output.WriteBool(Hidden);
      }
      if (SortOrder != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SortOrder);
      }
      if (BannerEnabled != false) {
        output.WriteRawTag(40);
        output.WriteBool(BannerEnabled);
      }
      if (BannerTitle.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(BannerTitle);
      }
      if (ImageUrl.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ImageUrl);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Description);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Category != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Hidden != false) {
        size += 1 + 1;
      }
      if (SortOrder != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SortOrder);
      }
      if (BannerEnabled != false) {
        size += 1 + 1;
      }
      if (BannerTitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BannerTitle);
      }
      if (ImageUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IapItemCategoryDisplay other) {
      if (other == null) {
        return;
      }
      if (other.Category != 0) {
        Category = other.Category;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Hidden != false) {
        Hidden = other.Hidden;
      }
      if (other.SortOrder != 0) {
        SortOrder = other.SortOrder;
      }
      if (other.BannerEnabled != false) {
        BannerEnabled = other.BannerEnabled;
      }
      if (other.BannerTitle.Length != 0) {
        BannerTitle = other.BannerTitle;
      }
      if (other.ImageUrl.Length != 0) {
        ImageUrl = other.ImageUrl;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            category_ = (global::POGOProtos.Enums.HoloIapItemCategory) input.ReadEnum();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Hidden = input.ReadBool();
            break;
          }
          case 32: {
            SortOrder = input.ReadInt32();
            break;
          }
          case 40: {
            BannerEnabled = input.ReadBool();
            break;
          }
          case 50: {
            BannerTitle = input.ReadString();
            break;
          }
          case 58: {
            ImageUrl = input.ReadString();
            break;
          }
          case 66: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
