// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Settings/Master/LuckyPokemonSettings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Settings.Master {

  /// <summary>Holder for reflection information generated from POGOProtos/Settings/Master/LuckyPokemonSettings.proto</summary>
  public static partial class LuckyPokemonSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Settings/Master/LuckyPokemonSettings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LuckyPokemonSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVQT0dPUHJvdG9zL1NldHRpbmdzL01hc3Rlci9MdWNreVBva2Vtb25TZXR0",
            "aW5ncy5wcm90bxIaUE9HT1Byb3Rvcy5TZXR0aW5ncy5NYXN0ZXIiQgoUTHVj",
            "a3lQb2tlbW9uU2V0dGluZ3MSKgoicG93ZXJfdXBfc3RhcmR1c3RfZGlzY291",
            "bnRfcGVyY2VudBgBIAEoAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Settings.Master.LuckyPokemonSettings), global::POGOProtos.Settings.Master.LuckyPokemonSettings.Parser, new[]{ "PowerUpStardustDiscountPercent" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LuckyPokemonSettings : pb::IMessage<LuckyPokemonSettings> {
    private static readonly pb::MessageParser<LuckyPokemonSettings> _parser = new pb::MessageParser<LuckyPokemonSettings>(() => new LuckyPokemonSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LuckyPokemonSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Settings.Master.LuckyPokemonSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LuckyPokemonSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LuckyPokemonSettings(LuckyPokemonSettings other) : this() {
      powerUpStardustDiscountPercent_ = other.powerUpStardustDiscountPercent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LuckyPokemonSettings Clone() {
      return new LuckyPokemonSettings(this);
    }

    /// <summary>Field number for the "power_up_stardust_discount_percent" field.</summary>
    public const int PowerUpStardustDiscountPercentFieldNumber = 1;
    private float powerUpStardustDiscountPercent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float PowerUpStardustDiscountPercent {
      get { return powerUpStardustDiscountPercent_; }
      set {
        powerUpStardustDiscountPercent_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LuckyPokemonSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LuckyPokemonSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PowerUpStardustDiscountPercent, other.PowerUpStardustDiscountPercent)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PowerUpStardustDiscountPercent != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PowerUpStardustDiscountPercent);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PowerUpStardustDiscountPercent != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(PowerUpStardustDiscountPercent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PowerUpStardustDiscountPercent != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LuckyPokemonSettings other) {
      if (other == null) {
        return;
      }
      if (other.PowerUpStardustDiscountPercent != 0F) {
        PowerUpStardustDiscountPercent = other.PowerUpStardustDiscountPercent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            PowerUpStardustDiscountPercent = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
