// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Data/Telemetry/ChangeArTelemetry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Telemetry {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Telemetry/ChangeArTelemetry.proto</summary>
  public static partial class ChangeArTelemetryReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Telemetry/ChangeArTelemetry.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChangeArTelemetryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFQT0dPUHJvdG9zL0RhdGEvVGVsZW1ldHJ5L0NoYW5nZUFyVGVsZW1ldHJ5",
            "LnByb3RvEhlQT0dPUHJvdG9zLkRhdGEuVGVsZW1ldHJ5IkAKEUNoYW5nZUFy",
            "VGVsZW1ldHJ5EhIKCmFyX2VuYWJsZWQYASABKAgSFwoPYXJfcGx1c19lbmFi",
            "bGVkGAIgASgIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Telemetry.ChangeArTelemetry), global::POGOProtos.Data.Telemetry.ChangeArTelemetry.Parser, new[]{ "ArEnabled", "ArPlusEnabled" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChangeArTelemetry : pb::IMessage<ChangeArTelemetry> {
    private static readonly pb::MessageParser<ChangeArTelemetry> _parser = new pb::MessageParser<ChangeArTelemetry>(() => new ChangeArTelemetry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChangeArTelemetry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Telemetry.ChangeArTelemetryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChangeArTelemetry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChangeArTelemetry(ChangeArTelemetry other) : this() {
      arEnabled_ = other.arEnabled_;
      arPlusEnabled_ = other.arPlusEnabled_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChangeArTelemetry Clone() {
      return new ChangeArTelemetry(this);
    }

    /// <summary>Field number for the "ar_enabled" field.</summary>
    public const int ArEnabledFieldNumber = 1;
    private bool arEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ArEnabled {
      get { return arEnabled_; }
      set {
        arEnabled_ = value;
      }
    }

    /// <summary>Field number for the "ar_plus_enabled" field.</summary>
    public const int ArPlusEnabledFieldNumber = 2;
    private bool arPlusEnabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ArPlusEnabled {
      get { return arPlusEnabled_; }
      set {
        arPlusEnabled_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChangeArTelemetry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChangeArTelemetry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ArEnabled != other.ArEnabled) return false;
      if (ArPlusEnabled != other.ArPlusEnabled) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ArEnabled != false) hash ^= ArEnabled.GetHashCode();
      if (ArPlusEnabled != false) hash ^= ArPlusEnabled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ArEnabled != false) {
        output.WriteRawTag(8);
        output.WriteBool(ArEnabled);
      }
      if (ArPlusEnabled != false) {
        output.WriteRawTag(16);
        output.WriteBool(ArPlusEnabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ArEnabled != false) {
        size += 1 + 1;
      }
      if (ArPlusEnabled != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChangeArTelemetry other) {
      if (other == null) {
        return;
      }
      if (other.ArEnabled != false) {
        ArEnabled = other.ArEnabled;
      }
      if (other.ArPlusEnabled != false) {
        ArPlusEnabled = other.ArPlusEnabled;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ArEnabled = input.ReadBool();
            break;
          }
          case 16: {
            ArPlusEnabled = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
