// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Quests/QuestGoal.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Quests {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Quests/QuestGoal.proto</summary>
  public static partial class QuestGoalReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Quests/QuestGoal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuestGoalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZQT0dPUHJvdG9zL0RhdGEvUXVlc3RzL1F1ZXN0R29hbC5wcm90bxIWUE9H",
            "T1Byb3Rvcy5EYXRhLlF1ZXN0cyKMAQoJUXVlc3RHb2FsEkEKC29wdGlvbl90",
            "eXBlGAEgASgOMiwuUE9HT1Byb3Rvcy5EYXRhLlF1ZXN0cy5RdWVzdEdvYWwu",
            "T3B0aW9uVHlwZRIOCgZ0YXJnZXQYAiABKAUiLAoKT3B0aW9uVHlwZRIJCgVV",
            "TlNFVBAAEhMKD09GX1BPS0VNT05fVFlQRRABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Quests.QuestGoal), global::POGOProtos.Data.Quests.QuestGoal.Parser, new[]{ "OptionType", "Target" }, null, new[]{ typeof(global::POGOProtos.Data.Quests.QuestGoal.Types.OptionType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class QuestGoal : pb::IMessage<QuestGoal> {
    private static readonly pb::MessageParser<QuestGoal> _parser = new pb::MessageParser<QuestGoal>(() => new QuestGoal());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuestGoal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Quests.QuestGoalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestGoal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestGoal(QuestGoal other) : this() {
      optionType_ = other.optionType_;
      target_ = other.target_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QuestGoal Clone() {
      return new QuestGoal(this);
    }

    /// <summary>Field number for the "option_type" field.</summary>
    public const int OptionTypeFieldNumber = 1;
    private global::POGOProtos.Data.Quests.QuestGoal.Types.OptionType optionType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Quests.QuestGoal.Types.OptionType OptionType {
      get { return optionType_; }
      set {
        optionType_ = value;
      }
    }

    /// <summary>Field number for the "target" field.</summary>
    public const int TargetFieldNumber = 2;
    private int target_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Target {
      get { return target_; }
      set {
        target_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QuestGoal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QuestGoal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OptionType != other.OptionType) return false;
      if (Target != other.Target) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OptionType != 0) hash ^= OptionType.GetHashCode();
      if (Target != 0) hash ^= Target.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OptionType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OptionType);
      }
      if (Target != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Target);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OptionType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OptionType);
      }
      if (Target != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Target);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QuestGoal other) {
      if (other == null) {
        return;
      }
      if (other.OptionType != 0) {
        OptionType = other.OptionType;
      }
      if (other.Target != 0) {
        Target = other.Target;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            optionType_ = (global::POGOProtos.Data.Quests.QuestGoal.Types.OptionType) input.ReadEnum();
            break;
          }
          case 16: {
            Target = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the QuestGoal message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum OptionType {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("OF_POKEMON_TYPE")] OfPokemonType = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
