// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/ClientInbox.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/ClientInbox.proto</summary>
  public static partial class ClientInboxReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/ClientInbox.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientInboxReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFQT0dPUHJvdG9zL0RhdGEvQ2xpZW50SW5ib3gucHJvdG8SD1BPR09Qcm90",
            "b3MuRGF0YRomUE9HT1Byb3Rvcy9EYXRhL1RlbXBsYXRlVmFyaWFibGUucHJv",
            "dG8aIlBPR09Qcm90b3MvRGF0YS9Ob3RpZmljYXRpb24ucHJvdG8igQEKC0Ns",
            "aWVudEluYm94EjQKDW5vdGlmaWNhdGlvbnMYASADKAsyHS5QT0dPUHJvdG9z",
            "LkRhdGEuTm90aWZpY2F0aW9uEjwKEWJ1aWx0aW5fdmFyaWFibGVzGAIgAygL",
            "MiEuUE9HT1Byb3Rvcy5EYXRhLlRlbXBsYXRlVmFyaWFibGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.TemplateVariableReflection.Descriptor, global::POGOProtos.Data.NotificationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.ClientInbox), global::POGOProtos.Data.ClientInbox.Parser, new[]{ "Notifications", "BuiltinVariables" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientInbox : pb::IMessage<ClientInbox> {
    private static readonly pb::MessageParser<ClientInbox> _parser = new pb::MessageParser<ClientInbox>(() => new ClientInbox());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientInbox> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.ClientInboxReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInbox() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInbox(ClientInbox other) : this() {
      notifications_ = other.notifications_.Clone();
      builtinVariables_ = other.builtinVariables_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientInbox Clone() {
      return new ClientInbox(this);
    }

    /// <summary>Field number for the "notifications" field.</summary>
    public const int NotificationsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Notification> _repeated_notifications_codec
        = pb::FieldCodec.ForMessage(10, global::POGOProtos.Data.Notification.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Notification> notifications_ = new pbc::RepeatedField<global::POGOProtos.Data.Notification>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Notification> Notifications {
      get { return notifications_; }
    }

    /// <summary>Field number for the "builtin_variables" field.</summary>
    public const int BuiltinVariablesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.TemplateVariable> _repeated_builtinVariables_codec
        = pb::FieldCodec.ForMessage(18, global::POGOProtos.Data.TemplateVariable.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.TemplateVariable> builtinVariables_ = new pbc::RepeatedField<global::POGOProtos.Data.TemplateVariable>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.TemplateVariable> BuiltinVariables {
      get { return builtinVariables_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientInbox);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientInbox other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!notifications_.Equals(other.notifications_)) return false;
      if(!builtinVariables_.Equals(other.builtinVariables_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= notifications_.GetHashCode();
      hash ^= builtinVariables_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      notifications_.WriteTo(output, _repeated_notifications_codec);
      builtinVariables_.WriteTo(output, _repeated_builtinVariables_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += notifications_.CalculateSize(_repeated_notifications_codec);
      size += builtinVariables_.CalculateSize(_repeated_builtinVariables_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientInbox other) {
      if (other == null) {
        return;
      }
      notifications_.Add(other.notifications_);
      builtinVariables_.Add(other.builtinVariables_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            notifications_.AddEntriesFrom(input, _repeated_notifications_codec);
            break;
          }
          case 18: {
            builtinVariables_.AddEntriesFrom(input, _repeated_builtinVariables_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
