// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/FetchAllNewsResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/FetchAllNewsResponse.proto</summary>
  public static partial class FetchAllNewsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/FetchAllNewsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FetchAllNewsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjpQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL0ZldGNoQWxsTmV3",
            "c1Jlc3BvbnNlLnByb3RvEh9QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9u",
            "c2VzGiZQT0dPUHJvdG9zL0RhdGEvTmV3cy9DdXJyZW50TmV3cy5wcm90byLS",
            "AQoURmV0Y2hBbGxOZXdzUmVzcG9uc2USTAoGcmVzdWx0GAEgASgOMjwuUE9H",
            "T1Byb3Rvcy5OZXR3b3JraW5nLlJlc3BvbnNlcy5GZXRjaEFsbE5ld3NSZXNw",
            "b25zZS5SZXN1bHQSNwoMY3VycmVudF9uZXdzGAIgASgLMiEuUE9HT1Byb3Rv",
            "cy5EYXRhLk5ld3MuQ3VycmVudE5ld3MiMwoGUmVzdWx0EgkKBVVOU0VUEAAS",
            "CwoHU1VDQ0VTUxABEhEKDU5PX05FV1NfRk9VTkQQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.News.CurrentNewsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.FetchAllNewsResponse), global::POGOProtos.Networking.Responses.FetchAllNewsResponse.Parser, new[]{ "Result", "CurrentNews" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.FetchAllNewsResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FetchAllNewsResponse : pb::IMessage<FetchAllNewsResponse> {
    private static readonly pb::MessageParser<FetchAllNewsResponse> _parser = new pb::MessageParser<FetchAllNewsResponse>(() => new FetchAllNewsResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FetchAllNewsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.FetchAllNewsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllNewsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllNewsResponse(FetchAllNewsResponse other) : this() {
      result_ = other.result_;
      CurrentNews = other.currentNews_ != null ? other.CurrentNews.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FetchAllNewsResponse Clone() {
      return new FetchAllNewsResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.FetchAllNewsResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.FetchAllNewsResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "current_news" field.</summary>
    public const int CurrentNewsFieldNumber = 2;
    private global::POGOProtos.Data.News.CurrentNews currentNews_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.News.CurrentNews CurrentNews {
      get { return currentNews_; }
      set {
        currentNews_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FetchAllNewsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FetchAllNewsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(CurrentNews, other.CurrentNews)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (currentNews_ != null) hash ^= CurrentNews.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (currentNews_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CurrentNews);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (currentNews_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentNews);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FetchAllNewsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.currentNews_ != null) {
        if (currentNews_ == null) {
          currentNews_ = new global::POGOProtos.Data.News.CurrentNews();
        }
        CurrentNews.MergeFrom(other.CurrentNews);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.FetchAllNewsResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (currentNews_ == null) {
              currentNews_ = new global::POGOProtos.Data.News.CurrentNews();
            }
            input.ReadMessage(currentNews_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the FetchAllNewsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("NO_NEWS_FOUND")] NoNewsFound = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
