// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: POGOProtos/Networking/Requests/Social/SaveSocialPlayerSettingsMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Requests.Social {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Requests/Social/SaveSocialPlayerSettingsMessage.proto</summary>
  public static partial class SaveSocialPlayerSettingsMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Requests/Social/SaveSocialPlayerSettingsMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SaveSocialPlayerSettingsMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CktQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVxdWVzdHMvU29jaWFsL1NhdmVT",
            "b2NpYWxQbGF5ZXJTZXR0aW5nc01lc3NhZ2UucHJvdG8SJVBPR09Qcm90b3Mu",
            "TmV0d29ya2luZy5SZXF1ZXN0cy5Tb2NpYWwaLlBPR09Qcm90b3MvU2V0dGlu",
            "Z3MvU29jaWFsUGxheWVyU2V0dGluZ3MucHJvdG8iXgofU2F2ZVNvY2lhbFBs",
            "YXllclNldHRpbmdzTWVzc2FnZRI7CghzZXR0aW5ncxgBIAEoCzIpLlBPR09Q",
            "cm90b3MuU2V0dGluZ3MuU29jaWFsUGxheWVyU2V0dGluZ3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Settings.SocialPlayerSettingsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Requests.Social.SaveSocialPlayerSettingsMessage), global::POGOProtos.Networking.Requests.Social.SaveSocialPlayerSettingsMessage.Parser, new[]{ "Settings" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SaveSocialPlayerSettingsMessage : pb::IMessage<SaveSocialPlayerSettingsMessage> {
    private static readonly pb::MessageParser<SaveSocialPlayerSettingsMessage> _parser = new pb::MessageParser<SaveSocialPlayerSettingsMessage>(() => new SaveSocialPlayerSettingsMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SaveSocialPlayerSettingsMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Requests.Social.SaveSocialPlayerSettingsMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveSocialPlayerSettingsMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveSocialPlayerSettingsMessage(SaveSocialPlayerSettingsMessage other) : this() {
      settings_ = other.settings_ != null ? other.settings_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveSocialPlayerSettingsMessage Clone() {
      return new SaveSocialPlayerSettingsMessage(this);
    }

    /// <summary>Field number for the "settings" field.</summary>
    public const int SettingsFieldNumber = 1;
    private global::POGOProtos.Settings.SocialPlayerSettings settings_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Settings.SocialPlayerSettings Settings {
      get { return settings_; }
      set {
        settings_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SaveSocialPlayerSettingsMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SaveSocialPlayerSettingsMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Settings, other.Settings)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (settings_ != null) hash ^= Settings.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (settings_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Settings);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (settings_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Settings);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SaveSocialPlayerSettingsMessage other) {
      if (other == null) {
        return;
      }
      if (other.settings_ != null) {
        if (settings_ == null) {
          settings_ = new global::POGOProtos.Settings.SocialPlayerSettings();
        }
        Settings.MergeFrom(other.Settings);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (settings_ == null) {
              settings_ = new global::POGOProtos.Settings.SocialPlayerSettings();
            }
            input.ReadMessage(settings_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
